//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.21 at 11:51:31 PM IST 
//


package com.oracle.oep.brm.opcodes;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}CUS_FLD_ADDON_PLAN_NAME"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}CUS_FLD_COM_PLAN_NAME"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}PACKAGE_ID"/>
 *       &lt;/sequence>
 *       &lt;attribute name="elem" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cusfldaddonplanname",
    "cusfldcomplanname",
    "packageid"
})
@XmlRootElement(name = "CUS_FLD_ADDON_PKG")
public class CUSFLDADDONPKG {

    @XmlElement(name = "CUS_FLD_ADDON_PLAN_NAME", required = true)
    protected String cusfldaddonplanname;
    @XmlElement(name = "CUS_FLD_COM_PLAN_NAME", required = true)
    protected String cusfldcomplanname;
    @XmlElement(name = "PACKAGE_ID", required = true)
    protected String packageid;
    @XmlAttribute(name = "elem", required = true)
    protected BigInteger elem;

    /**
     * Gets the value of the cusfldaddonplanname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSFLDADDONPLANNAME() {
        return cusfldaddonplanname;
    }

    /**
     * Sets the value of the cusfldaddonplanname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSFLDADDONPLANNAME(String value) {
        this.cusfldaddonplanname = value;
    }

    /**
     * Gets the value of the cusfldcomplanname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSFLDCOMPLANNAME() {
        return cusfldcomplanname;
    }

    /**
     * Sets the value of the cusfldcomplanname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSFLDCOMPLANNAME(String value) {
        this.cusfldcomplanname = value;
    }

    /**
     * Gets the value of the packageid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPACKAGEID() {
        return packageid;
    }

    /**
     * Sets the value of the packageid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPACKAGEID(String value) {
        this.packageid = value;
    }

    /**
     * Gets the value of the elem property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getElem() {
        return elem;
    }

    /**
     * Sets the value of the elem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setElem(BigInteger value) {
        this.elem = value;
    }

}
