//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.21 at 11:51:31 PM IST 
//


package com.oracle.oep.brm.opcodes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}ERROR_CODE"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}ERROR_DESCR"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}CUS_FLD_ADDON_PKG" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}POID"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}STATUS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorcode",
    "errordescr",
    "cusfldaddonpkg",
    "poid",
    "status"
})
@XmlRootElement(name = "CUS_OP_CUST_INCOMPATIBLE_ADDON_outputFlist")
public class CUSOPCUSTINCOMPATIBLEADDONOutputFlist {

    @XmlElement(name = "ERROR_CODE", required = true)
    protected String errorcode;
    @XmlElement(name = "ERROR_DESCR", required = true)
    protected String errordescr;
    @XmlElement(name = "CUS_FLD_ADDON_PKG", required = true)
    protected List<CUSFLDADDONPKG> cusfldaddonpkg;
    @XmlElement(name = "POID", required = true)
    protected String poid;
    @XmlElement(name = "STATUS", required = true)
    protected String status;

    /**
     * Gets the value of the errorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORCODE() {
        return errorcode;
    }

    /**
     * Sets the value of the errorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORCODE(String value) {
        this.errorcode = value;
    }

    /**
     * Gets the value of the errordescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORDESCR() {
        return errordescr;
    }

    /**
     * Sets the value of the errordescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORDESCR(String value) {
        this.errordescr = value;
    }

    /**
     * Gets the value of the cusfldaddonpkg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cusfldaddonpkg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCUSFLDADDONPKG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CUSFLDADDONPKG }
     * 
     * 
     */
    public List<CUSFLDADDONPKG> getCUSFLDADDONPKG() {
        if (cusfldaddonpkg == null) {
            cusfldaddonpkg = new ArrayList<CUSFLDADDONPKG>();
        }
        return this.cusfldaddonpkg;
    }

    /**
     * Gets the value of the poid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOID() {
        return poid;
    }

    /**
     * Sets the value of the poid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOID(String value) {
        this.poid = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }

}
