//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.28 at 07:04:43 PM IST 
//


package com.oracle.oep.brm.opcodes;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}ERROR_CODE"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}ERROR_DESCR"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}ACCOUNT_NO"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}POID"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}PROGRAM_NAME"/>
 *         &lt;element ref="{http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes}STATUS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorcode",
    "errordescr",
    "accountno",
    "poid",
    "programname",
    "status"
})
@XmlRootElement(name = "CUS_OP_CC_UPDATE_SERVICE_outputFlist")
public class CUSOPCCUPDATESERVICEOutputFlist {

    @XmlElement(name = "ERROR_CODE", required = true)
    protected BigInteger errorcode;
    @XmlElement(name = "ERROR_DESCR", required = true)
    protected String errordescr;
    @XmlElement(name = "ACCOUNT_NO", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String accountno;
    @XmlElement(name = "POID", required = true)
    protected String poid;
    @XmlElement(name = "PROGRAM_NAME", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String programname;
    @XmlElement(name = "STATUS", required = true)
    protected BigInteger status;

    /**
     * Gets the value of the errorcode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getERRORCODE() {
        return errorcode;
    }

    /**
     * Sets the value of the errorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setERRORCODE(BigInteger value) {
        this.errorcode = value;
    }

    /**
     * Gets the value of the errordescr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRORDESCR() {
        return errordescr;
    }

    /**
     * Sets the value of the errordescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRORDESCR(String value) {
        this.errordescr = value;
    }

    /**
     * Gets the value of the accountno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTNO() {
        return accountno;
    }

    /**
     * Sets the value of the accountno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTNO(String value) {
        this.accountno = value;
    }

    /**
     * Gets the value of the poid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOID() {
        return poid;
    }

    /**
     * Sets the value of the poid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOID(String value) {
        this.poid = value;
    }

    /**
     * Gets the value of the programname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROGRAMNAME() {
        return programname;
    }

    /**
     * Sets the value of the programname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROGRAMNAME(String value) {
        this.programname = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTATUS(BigInteger value) {
        this.status = value;
    }

}
