//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.11 at 11:07:29 PM IST 
//


package com.oracle.oep.brmorder.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/communications/schemas/CRMSync}BarringAction"/>
 *         &lt;element ref="{http://xmlns.oracle.com/communications/schemas/CRMSync}BarringLevel" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/communications/schemas/CRMSync}AccountNo" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/communications/schemas/CRMSync}CollectionNotifyContacts" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/communications/schemas/CRMSync}Collservices" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="InstanceId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "barringAction",
    "barringLevel",
    "accountNo",
    "collectionNotifyContacts",
    "collservices"
})
@XmlRootElement(name = "CollectionsActionBarring")
public class CollectionsActionBarring {

    @XmlElement(name = "BarringAction", required = true)
    protected String barringAction;
    @XmlElement(name = "BarringLevel")
    protected String barringLevel;
    @XmlElement(name = "AccountNo")
    protected String accountNo;
    @XmlElement(name = "CollectionNotifyContacts")
    protected List<CollectionNotifyContacts> collectionNotifyContacts;
    @XmlElement(name = "Collservices")
    protected List<Collservices> collservices;
    @XmlAttribute(name = "InstanceId", required = true)
    protected String instanceId;

    /**
     * Gets the value of the barringAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarringAction() {
        return barringAction;
    }

    /**
     * Sets the value of the barringAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarringAction(String value) {
        this.barringAction = value;
    }

    /**
     * Gets the value of the barringLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarringLevel() {
        return barringLevel;
    }

    /**
     * Sets the value of the barringLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarringLevel(String value) {
        this.barringLevel = value;
    }

    /**
     * Gets the value of the accountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * Sets the value of the accountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNo(String value) {
        this.accountNo = value;
    }

    /**
     * Gets the value of the collectionNotifyContacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the collectionNotifyContacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCollectionNotifyContacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CollectionNotifyContacts }
     * 
     * 
     */
    public List<CollectionNotifyContacts> getCollectionNotifyContacts() {
        if (collectionNotifyContacts == null) {
            collectionNotifyContacts = new ArrayList<CollectionNotifyContacts>();
        }
        return this.collectionNotifyContacts;
    }

    /**
     * Gets the value of the collservices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the collservices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCollservices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Collservices }
     * 
     * 
     */
    public List<Collservices> getCollservices() {
        if (collservices == null) {
            collservices = new ArrayList<Collservices>();
        }
        return this.collservices;
    }

    /**
     * Gets the value of the instanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * Sets the value of the instanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }

}
