//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.20 at 10:21:35 AM IST 
//


package com.oracle.oep.brmorder.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountObj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BarringAction" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="BarringLevel" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="EmailAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContactNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SuspendedIndicator" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="PrepaidLifecycleBarringServices">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PlanName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ServiceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MSISDN" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ActionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BarringType" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ElementId" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="InstanceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountNo",
    "accountObj",
    "barringAction",
    "barringLevel",
    "emailAddr",
    "contactNo",
    "suspendedIndicator",
    "prepaidLifecycleBarringServices"
})
@XmlRootElement(name = "PrepaidLifecycleBarring")
public class PrepaidLifecycleBarring {

    @XmlElement(name = "AccountNo", required = true)
    protected String accountNo;
    @XmlElement(name = "AccountObj", required = true)
    protected String accountObj;
    @XmlElement(name = "BarringAction")
    protected byte barringAction;
    @XmlElement(name = "BarringLevel")
    protected byte barringLevel;
    @XmlElement(name = "EmailAddr", required = true)
    protected String emailAddr;
    @XmlElement(name = "ContactNo")
    protected long contactNo;
    @XmlElement(name = "SuspendedIndicator")
    protected byte suspendedIndicator;
    @XmlElement(name = "PrepaidLifecycleBarringServices", required = true)
    protected PrepaidLifecycleBarring.PrepaidLifecycleBarringServices prepaidLifecycleBarringServices;
    @XmlAttribute(name = "InstanceId")
    protected String instanceId;

    /**
     * Gets the value of the accountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * Sets the value of the accountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNo(String value) {
        this.accountNo = value;
    }

    /**
     * Gets the value of the accountObj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountObj() {
        return accountObj;
    }

    /**
     * Sets the value of the accountObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountObj(String value) {
        this.accountObj = value;
    }

    /**
     * Gets the value of the barringAction property.
     * 
     */
    public byte getBarringAction() {
        return barringAction;
    }

    /**
     * Sets the value of the barringAction property.
     * 
     */
    public void setBarringAction(byte value) {
        this.barringAction = value;
    }

    /**
     * Gets the value of the barringLevel property.
     * 
     */
    public byte getBarringLevel() {
        return barringLevel;
    }

    /**
     * Sets the value of the barringLevel property.
     * 
     */
    public void setBarringLevel(byte value) {
        this.barringLevel = value;
    }

    /**
     * Gets the value of the emailAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddr() {
        return emailAddr;
    }

    /**
     * Sets the value of the emailAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddr(String value) {
        this.emailAddr = value;
    }

    /**
     * Gets the value of the contactNo property.
     * 
     */
    public long getContactNo() {
        return contactNo;
    }

    /**
     * Sets the value of the contactNo property.
     * 
     */
    public void setContactNo(long value) {
        this.contactNo = value;
    }

    /**
     * Gets the value of the suspendedIndicator property.
     * 
     */
    public byte getSuspendedIndicator() {
        return suspendedIndicator;
    }

    /**
     * Sets the value of the suspendedIndicator property.
     * 
     */
    public void setSuspendedIndicator(byte value) {
        this.suspendedIndicator = value;
    }

    /**
     * Gets the value of the prepaidLifecycleBarringServices property.
     * 
     * @return
     *     possible object is
     *     {@link PrepaidLifecycleBarring.PrepaidLifecycleBarringServices }
     *     
     */
    public PrepaidLifecycleBarring.PrepaidLifecycleBarringServices getPrepaidLifecycleBarringServices() {
        return prepaidLifecycleBarringServices;
    }

    /**
     * Sets the value of the prepaidLifecycleBarringServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrepaidLifecycleBarring.PrepaidLifecycleBarringServices }
     *     
     */
    public void setPrepaidLifecycleBarringServices(PrepaidLifecycleBarring.PrepaidLifecycleBarringServices value) {
        this.prepaidLifecycleBarringServices = value;
    }

    /**
     * Gets the value of the instanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * Sets the value of the instanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceId(String value) {
        this.instanceId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PlanName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ServiceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MSISDN" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ActionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BarringType" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ElementId" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "planName",
        "serviceIdentifier",
        "msisdn",
        "actionName",
        "barringType"
    })
    public static class PrepaidLifecycleBarringServices {

        @XmlElement(name = "PlanName", required = true)
        protected String planName;
        @XmlElement(name = "ServiceIdentifier", required = true)
        protected String serviceIdentifier;
        @XmlElement(name = "MSISDN")
        protected long msisdn;
        @XmlElement(name = "ActionName", required = true)
        protected String actionName;
        @XmlElement(name = "BarringType")
        protected byte barringType;
        @XmlAttribute(name = "ElementId")
        protected Byte elementId;

        /**
         * Gets the value of the planName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanName() {
            return planName;
        }

        /**
         * Sets the value of the planName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanName(String value) {
            this.planName = value;
        }

        /**
         * Gets the value of the serviceIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServiceIdentifier() {
            return serviceIdentifier;
        }

        /**
         * Sets the value of the serviceIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServiceIdentifier(String value) {
            this.serviceIdentifier = value;
        }

        /**
         * Gets the value of the msisdn property.
         * 
         */
        public long getMSISDN() {
            return msisdn;
        }

        /**
         * Sets the value of the msisdn property.
         * 
         */
        public void setMSISDN(long value) {
            this.msisdn = value;
        }

        /**
         * Gets the value of the actionName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActionName() {
            return actionName;
        }

        /**
         * Sets the value of the actionName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActionName(String value) {
            this.actionName = value;
        }

        /**
         * Gets the value of the barringType property.
         * 
         */
        public byte getBarringType() {
            return barringType;
        }

        /**
         * Sets the value of the barringType property.
         * 
         */
        public void setBarringType(byte value) {
            this.barringType = value;
        }

        /**
         * Gets the value of the elementId property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getElementId() {
            return elementId;
        }

        /**
         * Sets the value of the elementId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setElementId(Byte value) {
            this.elementId = value;
        }

    }

}
