//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 06:34:48 PM IST 
//


package com.oracle.oep.order.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddOrderServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddOrderServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MobileService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}AddOrderMobileType" minOccurs="0"/>
 *         &lt;element name="MobileBBService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}AddOrderMobileBBType" minOccurs="0"/>
 *         &lt;element name="ShortCodeService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}AddOrderShortCodeType" minOccurs="0"/>
 *         &lt;element name="M2MService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}AddOrderM2MType" minOccurs="0"/>
 *         &lt;element name="BulkSMSService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}AddOrderBulkSMSType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddOrderServiceType", propOrder = {
    "mobileService",
    "mobileBBService",
    "shortCodeService",
    "m2MService",
    "bulkSMSService"
})
public class AddOrderServiceType {

    @XmlElement(name = "MobileService")
    protected AddOrderMobileType mobileService;
    @XmlElement(name = "MobileBBService")
    protected AddOrderMobileBBType mobileBBService;
    @XmlElement(name = "ShortCodeService")
    protected AddOrderShortCodeType shortCodeService;
    @XmlElement(name = "M2MService")
    protected AddOrderM2MType m2MService;
    @XmlElement(name = "BulkSMSService")
    protected AddOrderBulkSMSType bulkSMSService;

    /**
     * Gets the value of the mobileService property.
     * 
     * @return
     *     possible object is
     *     {@link AddOrderMobileType }
     *     
     */
    public AddOrderMobileType getMobileService() {
        return mobileService;
    }

    /**
     * Sets the value of the mobileService property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddOrderMobileType }
     *     
     */
    public void setMobileService(AddOrderMobileType value) {
        this.mobileService = value;
    }

    /**
     * Gets the value of the mobileBBService property.
     * 
     * @return
     *     possible object is
     *     {@link AddOrderMobileBBType }
     *     
     */
    public AddOrderMobileBBType getMobileBBService() {
        return mobileBBService;
    }

    /**
     * Sets the value of the mobileBBService property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddOrderMobileBBType }
     *     
     */
    public void setMobileBBService(AddOrderMobileBBType value) {
        this.mobileBBService = value;
    }

    /**
     * Gets the value of the shortCodeService property.
     * 
     * @return
     *     possible object is
     *     {@link AddOrderShortCodeType }
     *     
     */
    public AddOrderShortCodeType getShortCodeService() {
        return shortCodeService;
    }

    /**
     * Sets the value of the shortCodeService property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddOrderShortCodeType }
     *     
     */
    public void setShortCodeService(AddOrderShortCodeType value) {
        this.shortCodeService = value;
    }

    /**
     * Gets the value of the m2MService property.
     * 
     * @return
     *     possible object is
     *     {@link AddOrderM2MType }
     *     
     */
    public AddOrderM2MType getM2MService() {
        return m2MService;
    }

    /**
     * Sets the value of the m2MService property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddOrderM2MType }
     *     
     */
    public void setM2MService(AddOrderM2MType value) {
        this.m2MService = value;
    }

    /**
     * Gets the value of the bulkSMSService property.
     * 
     * @return
     *     possible object is
     *     {@link AddOrderBulkSMSType }
     *     
     */
    public AddOrderBulkSMSType getBulkSMSService() {
        return bulkSMSService;
    }

    /**
     * Sets the value of the bulkSMSService property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddOrderBulkSMSType }
     *     
     */
    public void setBulkSMSService(AddOrderBulkSMSType value) {
        this.bulkSMSService = value;
    }

}
