//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 06:34:48 PM IST 
//


package com.oracle.oep.order.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DisconnectOrderServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisconnectOrderServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MobileService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DisconnectOrderMobileServiceType" minOccurs="0"/>
 *         &lt;element name="MobileBBService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DisconnectOrderMobileBBServiceType" minOccurs="0"/>
 *         &lt;element name="MobileShortCodeService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DisconnectOrderMobileShortCodeServiceType" minOccurs="0"/>
 *         &lt;element name="M2MService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DisconnectOrderM2MServiceType" minOccurs="0"/>
 *         &lt;element name="BulkSMSService" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DisconnectOrderBulkSMSServiceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisconnectOrderServiceType", propOrder = {
    "mobileService",
    "mobileBBService",
    "mobileShortCodeService",
    "m2MService",
    "bulkSMSService"
})
public class DisconnectOrderServiceType {

    @XmlElement(name = "MobileService")
    protected DisconnectOrderMobileServiceType mobileService;
    @XmlElement(name = "MobileBBService")
    protected DisconnectOrderMobileBBServiceType mobileBBService;
    @XmlElement(name = "MobileShortCodeService")
    protected DisconnectOrderMobileShortCodeServiceType mobileShortCodeService;
    @XmlElement(name = "M2MService")
    protected DisconnectOrderM2MServiceType m2MService;
    @XmlElement(name = "BulkSMSService")
    protected DisconnectOrderBulkSMSServiceType bulkSMSService;

    /**
     * Gets the value of the mobileService property.
     * 
     * @return
     *     possible object is
     *     {@link DisconnectOrderMobileServiceType }
     *     
     */
    public DisconnectOrderMobileServiceType getMobileService() {
        return mobileService;
    }

    /**
     * Sets the value of the mobileService property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisconnectOrderMobileServiceType }
     *     
     */
    public void setMobileService(DisconnectOrderMobileServiceType value) {
        this.mobileService = value;
    }

    /**
     * Gets the value of the mobileBBService property.
     * 
     * @return
     *     possible object is
     *     {@link DisconnectOrderMobileBBServiceType }
     *     
     */
    public DisconnectOrderMobileBBServiceType getMobileBBService() {
        return mobileBBService;
    }

    /**
     * Sets the value of the mobileBBService property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisconnectOrderMobileBBServiceType }
     *     
     */
    public void setMobileBBService(DisconnectOrderMobileBBServiceType value) {
        this.mobileBBService = value;
    }

    /**
     * Gets the value of the mobileShortCodeService property.
     * 
     * @return
     *     possible object is
     *     {@link DisconnectOrderMobileShortCodeServiceType }
     *     
     */
    public DisconnectOrderMobileShortCodeServiceType getMobileShortCodeService() {
        return mobileShortCodeService;
    }

    /**
     * Sets the value of the mobileShortCodeService property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisconnectOrderMobileShortCodeServiceType }
     *     
     */
    public void setMobileShortCodeService(DisconnectOrderMobileShortCodeServiceType value) {
        this.mobileShortCodeService = value;
    }

    /**
     * Gets the value of the m2MService property.
     * 
     * @return
     *     possible object is
     *     {@link DisconnectOrderM2MServiceType }
     *     
     */
    public DisconnectOrderM2MServiceType getM2MService() {
        return m2MService;
    }

    /**
     * Sets the value of the m2MService property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisconnectOrderM2MServiceType }
     *     
     */
    public void setM2MService(DisconnectOrderM2MServiceType value) {
        this.m2MService = value;
    }

    /**
     * Gets the value of the bulkSMSService property.
     * 
     * @return
     *     possible object is
     *     {@link DisconnectOrderBulkSMSServiceType }
     *     
     */
    public DisconnectOrderBulkSMSServiceType getBulkSMSService() {
        return bulkSMSService;
    }

    /**
     * Sets the value of the bulkSMSService property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisconnectOrderBulkSMSServiceType }
     *     
     */
    public void setBulkSMSService(DisconnectOrderBulkSMSServiceType value) {
        this.bulkSMSService = value;
    }

}
