//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.10 at 07:40:04 PM IST 
//


package com.oracle.oep.order.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModifyOrderShortCodeServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModifyOrderShortCodeServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChangePlan" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ChangePlanShortCodeOrderType" minOccurs="0"/>
 *         &lt;element name="ChangeShortCodeNumber" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ChangeShortCodeNumberOrderType" minOccurs="0"/>
 *         &lt;element name="AddRemoveAddon" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ChangeShortCodeAddOnOrderType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModifyOrderShortCodeServiceType", propOrder = {
    "changePlan",
    "changeShortCodeNumber",
    "addRemoveAddon"
})
public class ModifyOrderShortCodeServiceType {

    @XmlElement(name = "ChangePlan")
    protected ChangePlanShortCodeOrderType changePlan;
    @XmlElement(name = "ChangeShortCodeNumber")
    protected ChangeShortCodeNumberOrderType changeShortCodeNumber;
    @XmlElement(name = "AddRemoveAddon")
    protected ChangeShortCodeAddOnOrderType addRemoveAddon;

    /**
     * Gets the value of the changePlan property.
     * 
     * @return
     *     possible object is
     *     {@link ChangePlanShortCodeOrderType }
     *     
     */
    public ChangePlanShortCodeOrderType getChangePlan() {
        return changePlan;
    }

    /**
     * Sets the value of the changePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangePlanShortCodeOrderType }
     *     
     */
    public void setChangePlan(ChangePlanShortCodeOrderType value) {
        this.changePlan = value;
    }

    /**
     * Gets the value of the changeShortCodeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeShortCodeNumberOrderType }
     *     
     */
    public ChangeShortCodeNumberOrderType getChangeShortCodeNumber() {
        return changeShortCodeNumber;
    }

    /**
     * Sets the value of the changeShortCodeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeShortCodeNumberOrderType }
     *     
     */
    public void setChangeShortCodeNumber(ChangeShortCodeNumberOrderType value) {
        this.changeShortCodeNumber = value;
    }

    /**
     * Gets the value of the addRemoveAddon property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeShortCodeAddOnOrderType }
     *     
     */
    public ChangeShortCodeAddOnOrderType getAddRemoveAddon() {
        return addRemoveAddon;
    }

    /**
     * Sets the value of the addRemoveAddon property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeShortCodeAddOnOrderType }
     *     
     */
    public void setAddRemoveAddon(ChangeShortCodeAddOnOrderType value) {
        this.addRemoveAddon = value;
    }

}
