//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 06:32:32 PM IST 
//


package com.oracle.oep.order.model;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.oep.order.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Email_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "Email");
    private final static QName _ChangeReason_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ChangeReason");
    private final static QName _ServiceIdentifier_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ServiceIdentifier");
    private final static QName _SuspensionDuration_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "SuspensionDuration");
    private final static QName _DepositCurrency_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DepositCurrency");
    private final static QName _SIMDetails_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "SIMDetails");
    private final static QName _OrderType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderType");
    private final static QName _NewRoute_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "NewRoute");
    private final static QName _DepositMethod_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DepositMethod");
    private final static QName _BillingAccountId_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "BillingAccountId");
    private final static QName _OldServiceNumber_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OldServiceNumber");
    private final static QName _CugAction_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "CugAction");
    private final static QName _BarringLevel_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "BarringLevel");
    private final static QName _OrderId_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderId");
    private final static QName _NiceCategoryValue_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "NiceCategoryValue");
    private final static QName _SpendingCapMax_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "SpendingCapMax");
    private final static QName _NiceCategory_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "NiceCategory");
    private final static QName _DepositType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DepositType");
    private final static QName _DepositWaiver_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DepositWaiver");
    private final static QName _ChannelName_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ChannelName");
    private final static QName _DeviceType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DeviceType");
    private final static QName _SpendingCapMin_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "SpendingCapMin");
    private final static QName _Imsi_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "Imsi");
    private final static QName _MsIsdn_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "MsIsdn");
    private final static QName _ServiceNumber_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ServiceNumber");
    private final static QName _Action_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "Action");
    private final static QName _Options_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "Options");
    private final static QName _OverridenPrice_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OverridenPrice");
    private final static QName _OrderName_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderName");
    private final static QName _Reason_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "Reason");
    private final static QName _OldShortCodeNumber_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OldShortCodeNumber");
    private final static QName _CustomerAccountId_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "CustomerAccountId");
    private final static QName _BillingAccountName_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "BillingAccountName");
    private final static QName _CustomerName_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "CustomerName");
    private final static QName _DeviceMake_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DeviceMake");
    private final static QName _ShortCodeType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ShortCodeType");
    private final static QName _BulkSMSType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "BulkSMSType");
    private final static QName _OrderUserId_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderUserId");
    private final static QName _WaveOff_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "WaveOff");
    private final static QName _RoamingDeposit_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "RoamingDeposit");
    private final static QName _CreditScoreDate_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "CreditScoreDate");
    private final static QName _ServiceNo_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ServiceNo");
    private final static QName _CugId_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "CugId");
    private final static QName _HandSetDetails_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "HandSetDetails");
    private final static QName _TerminationCharge_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "TerminationCharge");
    private final static QName _ShortNumberAction_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ShortNumberAction");
    private final static QName _ChannelTrackingId_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ChannelTrackingId");
    private final static QName _OrderAction_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderAction");
    private final static QName _OrderCreatedDate_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderCreatedDate");
    private final static QName _UnsuspendFlag_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "UnsuspendFlag");
    private final static QName _BarringType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "BarringType");
    private final static QName _SuspendedIndicator_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "SuspendedIndicator");
    private final static QName _ServiceSuspensionDescription_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ServiceSuspensionDescription");
    private final static QName _CollectedOn_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "CollectedOn");
    private final static QName _WaveOffReason_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "WaveOffReason");
    private final static QName _OldMsIsdn_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OldMsIsdn");
    private final static QName _ServiceType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ServiceType");
    private final static QName _BarringAction_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "BarringAction");
    private final static QName _ContactNo_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ContactNo");
    private final static QName _DepositReceiptNo_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DepositReceiptNo");
    private final static QName _SimNo_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "SimNo");
    private final static QName _PlanType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "PlanType");
    private final static QName _PlanEndDate_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "PlanEndDate");
    private final static QName _AccountNo_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "AccountNo");
    private final static QName _ShortCodeNumber_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ShortCodeNumber");
    private final static QName _DepositDate_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DepositDate");
    private final static QName _DepositAmount_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DepositAmount");
    private final static QName _EmailId_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "EmailId");
    private final static QName _OrderServiceType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderServiceType");
    private final static QName _IdType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "IdType");
    private final static QName _SpendingCap_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "SpendingCap");
    private final static QName _NotificationLanguage_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "NotificationLanguage");
    private final static QName _OldSimNo_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OldSimNo");
    private final static QName _OrderStartDate_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderStartDate");
    private final static QName _AccountName_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "AccountName");
    private final static QName _PortType_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "PortType");
    private final static QName _ShortNumber_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ShortNumber");
    private final static QName _Id_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "Id");
    private final static QName _ServiceChargeFlag_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ServiceChargeFlag");
    private final static QName _OldShortNumber_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OldShortNumber");
    private final static QName _ContractStartDate_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ContractStartDate");
    private final static QName _DepositPayment_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DepositPayment");
    private final static QName _OrderCreatedDateMin_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderCreatedDateMin");
    private final static QName _PlanName_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "PlanName");
    private final static QName _ShortCodeCategory_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ShortCodeCategory");
    private final static QName _OrderStatus_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderStatus");
    private final static QName _WaiverReason_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "WaiverReason");
    private final static QName _SimChargeFlag_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "SimChargeFlag");
    private final static QName _CreditScore_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "CreditScore");
    private final static QName _OrderCreatedDateMax_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderCreatedDateMax");
    private final static QName _EarlyTerminationFlag_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "EarlyTerminationFlag");
    private final static QName _ContractEndDate_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ContractEndDate");
    private final static QName _OrderResumeDate_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "OrderResumeDate");
    private final static QName _CustomerAccountName_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "CustomerAccountName");
    private final static QName _TerminationNotes_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "TerminationNotes");
    private final static QName _BAAccountNo_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "BAAccountNo");
    private final static QName _DealName_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "DealName");
    private final static QName _PlanStartDate_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "PlanStartDate");
    private final static QName _ServiceLevelDeposit_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "ServiceLevelDeposit");
    private final static QName _PlanAction_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "PlanAction");
    private final static QName _AddOrderM2MTypePlan_QNAME = new QName("http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", "Plan");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.oep.order.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DepositPaymentType }
     * 
     */
    public DepositPaymentType createDepositPaymentType() {
        return new DepositPaymentType();
    }

    /**
     * Create an instance of {@link RetryOSMOrderRequest }
     * 
     */
    public RetryOSMOrderRequest createRetryOSMOrderRequest() {
        return new RetryOSMOrderRequest();
    }

    /**
     * Create an instance of {@link SIMDetailsType }
     * 
     */
    public SIMDetailsType createSIMDetailsType() {
        return new SIMDetailsType();
    }

    /**
     * Create an instance of {@link OrderEntryResponse }
     * 
     */
    public OrderEntryResponse createOrderEntryResponse() {
        return new OrderEntryResponse();
    }

    /**
     * Create an instance of {@link ProcessOrderResponseType }
     * 
     */
    public ProcessOrderResponseType createProcessOrderResponseType() {
        return new ProcessOrderResponseType();
    }

    /**
     * Create an instance of {@link ProcessQueryOrderResponseType }
     * 
     */
    public ProcessQueryOrderResponseType createProcessQueryOrderResponseType() {
        return new ProcessQueryOrderResponseType();
    }

    /**
     * Create an instance of {@link ProcessQueryOrderDetailsResponseType }
     * 
     */
    public ProcessQueryOrderDetailsResponseType createProcessQueryOrderDetailsResponseType() {
        return new ProcessQueryOrderDetailsResponseType();
    }

    /**
     * Create an instance of {@link RetryOSMOrderResponse }
     * 
     */
    public RetryOSMOrderResponse createRetryOSMOrderResponse() {
        return new RetryOSMOrderResponse();
    }

    /**
     * Create an instance of {@link OrderEntryRequest }
     * 
     */
    public OrderEntryRequest createOrderEntryRequest() {
        return new OrderEntryRequest();
    }

    /**
     * Create an instance of {@link ProcessAddOrderType }
     * 
     */
    public ProcessAddOrderType createProcessAddOrderType() {
        return new ProcessAddOrderType();
    }

    /**
     * Create an instance of {@link ProcessModifyOrderType }
     * 
     */
    public ProcessModifyOrderType createProcessModifyOrderType() {
        return new ProcessModifyOrderType();
    }

    /**
     * Create an instance of {@link ProcessSuspendOrderType }
     * 
     */
    public ProcessSuspendOrderType createProcessSuspendOrderType() {
        return new ProcessSuspendOrderType();
    }

    /**
     * Create an instance of {@link ProcessDisconnectOrderType }
     * 
     */
    public ProcessDisconnectOrderType createProcessDisconnectOrderType() {
        return new ProcessDisconnectOrderType();
    }

    /**
     * Create an instance of {@link ProcessNumberReleaseOrderType }
     * 
     */
    public ProcessNumberReleaseOrderType createProcessNumberReleaseOrderType() {
        return new ProcessNumberReleaseOrderType();
    }

    /**
     * Create an instance of {@link ProcessCugOrderType }
     * 
     */
    public ProcessCugOrderType createProcessCugOrderType() {
        return new ProcessCugOrderType();
    }

    /**
     * Create an instance of {@link ProcessManagePortInOrderType }
     * 
     */
    public ProcessManagePortInOrderType createProcessManagePortInOrderType() {
        return new ProcessManagePortInOrderType();
    }

    /**
     * Create an instance of {@link ProcessQueryOrderType }
     * 
     */
    public ProcessQueryOrderType createProcessQueryOrderType() {
        return new ProcessQueryOrderType();
    }

    /**
     * Create an instance of {@link ProcessQueryOrderDetailsType }
     * 
     */
    public ProcessQueryOrderDetailsType createProcessQueryOrderDetailsType() {
        return new ProcessQueryOrderDetailsType();
    }

    /**
     * Create an instance of {@link ProcessChangePlanReqType }
     * 
     */
    public ProcessChangePlanReqType createProcessChangePlanReqType() {
        return new ProcessChangePlanReqType();
    }

    /**
     * Create an instance of {@link ProcessAddOnManagmentType }
     * 
     */
    public ProcessAddOnManagmentType createProcessAddOnManagmentType() {
        return new ProcessAddOnManagmentType();
    }

    /**
     * Create an instance of {@link ProcessCallDivertReqType }
     * 
     */
    public ProcessCallDivertReqType createProcessCallDivertReqType() {
        return new ProcessCallDivertReqType();
    }

    /**
     * Create an instance of {@link ProcessCollectionBarringReqType }
     * 
     */
    public ProcessCollectionBarringReqType createProcessCollectionBarringReqType() {
        return new ProcessCollectionBarringReqType();
    }

    /**
     * Create an instance of {@link ProcessStartCancelOrderType }
     * 
     */
    public ProcessStartCancelOrderType createProcessStartCancelOrderType() {
        return new ProcessStartCancelOrderType();
    }

    /**
     * Create an instance of {@link ProcessUpdateServiceSuspensionDateType }
     * 
     */
    public ProcessUpdateServiceSuspensionDateType createProcessUpdateServiceSuspensionDateType() {
        return new ProcessUpdateServiceSuspensionDateType();
    }

    /**
     * Create an instance of {@link HandSetDetailsType }
     * 
     */
    public HandSetDetailsType createHandSetDetailsType() {
        return new HandSetDetailsType();
    }

    /**
     * Create an instance of {@link ModifyOrderMobileBBServiceType }
     * 
     */
    public ModifyOrderMobileBBServiceType createModifyOrderMobileBBServiceType() {
        return new ModifyOrderMobileBBServiceType();
    }

    /**
     * Create an instance of {@link SuspendOrderServiceType }
     * 
     */
    public SuspendOrderServiceType createSuspendOrderServiceType() {
        return new SuspendOrderServiceType();
    }

    /**
     * Create an instance of {@link ListOfOEPQueryOrderResponseType }
     * 
     */
    public ListOfOEPQueryOrderResponseType createListOfOEPQueryOrderResponseType() {
        return new ListOfOEPQueryOrderResponseType();
    }

    /**
     * Create an instance of {@link DisconnectOrderM2MServiceType }
     * 
     */
    public DisconnectOrderM2MServiceType createDisconnectOrderM2MServiceType() {
        return new DisconnectOrderM2MServiceType();
    }

    /**
     * Create an instance of {@link ListOfOEPOrderResponseType }
     * 
     */
    public ListOfOEPOrderResponseType createListOfOEPOrderResponseType() {
        return new ListOfOEPOrderResponseType();
    }

    /**
     * Create an instance of {@link ChangePlanActionPlanType }
     * 
     */
    public ChangePlanActionPlanType createChangePlanActionPlanType() {
        return new ChangePlanActionPlanType();
    }

    /**
     * Create an instance of {@link DisconnectOrderMobileServiceType }
     * 
     */
    public DisconnectOrderMobileServiceType createDisconnectOrderMobileServiceType() {
        return new DisconnectOrderMobileServiceType();
    }

    /**
     * Create an instance of {@link ChangeShortCodeNumberOrderType }
     * 
     */
    public ChangeShortCodeNumberOrderType createChangeShortCodeNumberOrderType() {
        return new ChangeShortCodeNumberOrderType();
    }

    /**
     * Create an instance of {@link FcaOrderType }
     * 
     */
    public FcaOrderType createFcaOrderType() {
        return new FcaOrderType();
    }

    /**
     * Create an instance of {@link OEPOrderResponseType }
     * 
     */
    public OEPOrderResponseType createOEPOrderResponseType() {
        return new OEPOrderResponseType();
    }

    /**
     * Create an instance of {@link ListOfOEPOrderAddType }
     * 
     */
    public ListOfOEPOrderAddType createListOfOEPOrderAddType() {
        return new ListOfOEPOrderAddType();
    }

    /**
     * Create an instance of {@link ChangeAddOnOrderType }
     * 
     */
    public ChangeAddOnOrderType createChangeAddOnOrderType() {
        return new ChangeAddOnOrderType();
    }

    /**
     * Create an instance of {@link ModifyOrderM2MServiceType }
     * 
     */
    public ModifyOrderM2MServiceType createModifyOrderM2MServiceType() {
        return new ModifyOrderM2MServiceType();
    }

    /**
     * Create an instance of {@link MNPDetailsType }
     * 
     */
    public MNPDetailsType createMNPDetailsType() {
        return new MNPDetailsType();
    }

    /**
     * Create an instance of {@link DisconnectOrderBulkSMSServiceType }
     * 
     */
    public DisconnectOrderBulkSMSServiceType createDisconnectOrderBulkSMSServiceType() {
        return new DisconnectOrderBulkSMSServiceType();
    }

    /**
     * Create an instance of {@link AddOrderShortCodeType }
     * 
     */
    public AddOrderShortCodeType createAddOrderShortCodeType() {
        return new AddOrderShortCodeType();
    }

    /**
     * Create an instance of {@link ChangeSIMOrderType }
     * 
     */
    public ChangeSIMOrderType createChangeSIMOrderType() {
        return new ChangeSIMOrderType();
    }

    /**
     * Create an instance of {@link AddActionPlanType }
     * 
     */
    public AddActionPlanType createAddActionPlanType() {
        return new AddActionPlanType();
    }

    /**
     * Create an instance of {@link ListOfOEPOrderSuspendType }
     * 
     */
    public ListOfOEPOrderSuspendType createListOfOEPOrderSuspendType() {
        return new ListOfOEPOrderSuspendType();
    }

    /**
     * Create an instance of {@link OEPOrderTaskResponseType }
     * 
     */
    public OEPOrderTaskResponseType createOEPOrderTaskResponseType() {
        return new OEPOrderTaskResponseType();
    }

    /**
     * Create an instance of {@link AddOrderServiceType }
     * 
     */
    public AddOrderServiceType createAddOrderServiceType() {
        return new AddOrderServiceType();
    }

    /**
     * Create an instance of {@link ChangeBulkSMSDetailsOrderType }
     * 
     */
    public ChangeBulkSMSDetailsOrderType createChangeBulkSMSDetailsOrderType() {
        return new ChangeBulkSMSDetailsOrderType();
    }

    /**
     * Create an instance of {@link DisconnectOrderMobileShortCodeServiceType }
     * 
     */
    public DisconnectOrderMobileShortCodeServiceType createDisconnectOrderMobileShortCodeServiceType() {
        return new DisconnectOrderMobileShortCodeServiceType();
    }

    /**
     * Create an instance of {@link AddOrderBulkSMSType }
     * 
     */
    public AddOrderBulkSMSType createAddOrderBulkSMSType() {
        return new AddOrderBulkSMSType();
    }

    /**
     * Create an instance of {@link AddOrderMobileBBType }
     * 
     */
    public AddOrderMobileBBType createAddOrderMobileBBType() {
        return new AddOrderMobileBBType();
    }

    /**
     * Create an instance of {@link ListOfOEPOrderDisconnectType }
     * 
     */
    public ListOfOEPOrderDisconnectType createListOfOEPOrderDisconnectType() {
        return new ListOfOEPOrderDisconnectType();
    }

    /**
     * Create an instance of {@link DisconnectOrderMobileBBServiceType }
     * 
     */
    public DisconnectOrderMobileBBServiceType createDisconnectOrderMobileBBServiceType() {
        return new DisconnectOrderMobileBBServiceType();
    }

    /**
     * Create an instance of {@link AddOrderM2MType }
     * 
     */
    public AddOrderM2MType createAddOrderM2MType() {
        return new AddOrderM2MType();
    }

    /**
     * Create an instance of {@link ModifyOrderShortCodeServiceType }
     * 
     */
    public ModifyOrderShortCodeServiceType createModifyOrderShortCodeServiceType() {
        return new ModifyOrderShortCodeServiceType();
    }

    /**
     * Create an instance of {@link ListOfOEPQueryOrderDetailsResponseType }
     * 
     */
    public ListOfOEPQueryOrderDetailsResponseType createListOfOEPQueryOrderDetailsResponseType() {
        return new ListOfOEPQueryOrderDetailsResponseType();
    }

    /**
     * Create an instance of {@link SuspendDisconnectOrderAllServiceType }
     * 
     */
    public SuspendDisconnectOrderAllServiceType createSuspendDisconnectOrderAllServiceType() {
        return new SuspendDisconnectOrderAllServiceType();
    }

    /**
     * Create an instance of {@link DisconnectOrderServiceType }
     * 
     */
    public DisconnectOrderServiceType createDisconnectOrderServiceType() {
        return new DisconnectOrderServiceType();
    }

    /**
     * Create an instance of {@link OEPOrderDetailResponseType }
     * 
     */
    public OEPOrderDetailResponseType createOEPOrderDetailResponseType() {
        return new OEPOrderDetailResponseType();
    }

    /**
     * Create an instance of {@link ChangeShortCodeAddOnOrderType }
     * 
     */
    public ChangeShortCodeAddOnOrderType createChangeShortCodeAddOnOrderType() {
        return new ChangeShortCodeAddOnOrderType();
    }

    /**
     * Create an instance of {@link ListOfOEPOrderModifyType }
     * 
     */
    public ListOfOEPOrderModifyType createListOfOEPOrderModifyType() {
        return new ListOfOEPOrderModifyType();
    }

    /**
     * Create an instance of {@link ChangePlanShortCodeOrderType }
     * 
     */
    public ChangePlanShortCodeOrderType createChangePlanShortCodeOrderType() {
        return new ChangePlanShortCodeOrderType();
    }

    /**
     * Create an instance of {@link SuspendOrderM2MServiceType }
     * 
     */
    public SuspendOrderM2MServiceType createSuspendOrderM2MServiceType() {
        return new SuspendOrderM2MServiceType();
    }

    /**
     * Create an instance of {@link BarringServicesType }
     * 
     */
    public BarringServicesType createBarringServicesType() {
        return new BarringServicesType();
    }

    /**
     * Create an instance of {@link SuspendOrderMobileShortCodeServiceType }
     * 
     */
    public SuspendOrderMobileShortCodeServiceType createSuspendOrderMobileShortCodeServiceType() {
        return new SuspendOrderMobileShortCodeServiceType();
    }

    /**
     * Create an instance of {@link ModifyOrderServiceType }
     * 
     */
    public ModifyOrderServiceType createModifyOrderServiceType() {
        return new ModifyOrderServiceType();
    }

    /**
     * Create an instance of {@link ChangeMsIsdnOrderType }
     * 
     */
    public ChangeMsIsdnOrderType createChangeMsIsdnOrderType() {
        return new ChangeMsIsdnOrderType();
    }

    /**
     * Create an instance of {@link ChangePlanOrderType }
     * 
     */
    public ChangePlanOrderType createChangePlanOrderType() {
        return new ChangePlanOrderType();
    }

    /**
     * Create an instance of {@link SuspendOrderMobileServiceType }
     * 
     */
    public SuspendOrderMobileServiceType createSuspendOrderMobileServiceType() {
        return new SuspendOrderMobileServiceType();
    }

    /**
     * Create an instance of {@link ModifyOrderMobileServiceType }
     * 
     */
    public ModifyOrderMobileServiceType createModifyOrderMobileServiceType() {
        return new ModifyOrderMobileServiceType();
    }

    /**
     * Create an instance of {@link SuspendOrderMobileBBServiceType }
     * 
     */
    public SuspendOrderMobileBBServiceType createSuspendOrderMobileBBServiceType() {
        return new SuspendOrderMobileBBServiceType();
    }

    /**
     * Create an instance of {@link AddOrderMobileType }
     * 
     */
    public AddOrderMobileType createAddOrderMobileType() {
        return new AddOrderMobileType();
    }

    /**
     * Create an instance of {@link SuspendOrderBulkSMSServiceType }
     * 
     */
    public SuspendOrderBulkSMSServiceType createSuspendOrderBulkSMSServiceType() {
        return new SuspendOrderBulkSMSServiceType();
    }

    /**
     * Create an instance of {@link ModifyOrderBulkSMSServiceType }
     * 
     */
    public ModifyOrderBulkSMSServiceType createModifyOrderBulkSMSServiceType() {
        return new ModifyOrderBulkSMSServiceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "Email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ChangeReason")
    public JAXBElement<String> createChangeReason(String value) {
        return new JAXBElement<String>(_ChangeReason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ServiceIdentifier")
    public JAXBElement<String> createServiceIdentifier(String value) {
        return new JAXBElement<String>(_ServiceIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "SuspensionDuration")
    public JAXBElement<String> createSuspensionDuration(String value) {
        return new JAXBElement<String>(_SuspensionDuration_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DepositCurrency")
    public JAXBElement<String> createDepositCurrency(String value) {
        return new JAXBElement<String>(_DepositCurrency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SIMDetailsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "SIMDetails")
    public JAXBElement<SIMDetailsType> createSIMDetails(SIMDetailsType value) {
        return new JAXBElement<SIMDetailsType>(_SIMDetails_QNAME, SIMDetailsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderType")
    public JAXBElement<String> createOrderType(String value) {
        return new JAXBElement<String>(_OrderType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "NewRoute")
    public JAXBElement<String> createNewRoute(String value) {
        return new JAXBElement<String>(_NewRoute_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DepositMethod")
    public JAXBElement<String> createDepositMethod(String value) {
        return new JAXBElement<String>(_DepositMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "BillingAccountId")
    public JAXBElement<String> createBillingAccountId(String value) {
        return new JAXBElement<String>(_BillingAccountId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OldServiceNumber")
    public JAXBElement<String> createOldServiceNumber(String value) {
        return new JAXBElement<String>(_OldServiceNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "CugAction")
    public JAXBElement<String> createCugAction(String value) {
        return new JAXBElement<String>(_CugAction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "BarringLevel")
    public JAXBElement<String> createBarringLevel(String value) {
        return new JAXBElement<String>(_BarringLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderId")
    public JAXBElement<String> createOrderId(String value) {
        return new JAXBElement<String>(_OrderId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "NiceCategoryValue")
    public JAXBElement<String> createNiceCategoryValue(String value) {
        return new JAXBElement<String>(_NiceCategoryValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "SpendingCapMax")
    public JAXBElement<String> createSpendingCapMax(String value) {
        return new JAXBElement<String>(_SpendingCapMax_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "NiceCategory")
    public JAXBElement<String> createNiceCategory(String value) {
        return new JAXBElement<String>(_NiceCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DepositType")
    public JAXBElement<String> createDepositType(String value) {
        return new JAXBElement<String>(_DepositType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DepositWaiver")
    public JAXBElement<String> createDepositWaiver(String value) {
        return new JAXBElement<String>(_DepositWaiver_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ChannelName")
    public JAXBElement<String> createChannelName(String value) {
        return new JAXBElement<String>(_ChannelName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DeviceType")
    public JAXBElement<String> createDeviceType(String value) {
        return new JAXBElement<String>(_DeviceType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "SpendingCapMin")
    public JAXBElement<String> createSpendingCapMin(String value) {
        return new JAXBElement<String>(_SpendingCapMin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "Imsi")
    public JAXBElement<String> createImsi(String value) {
        return new JAXBElement<String>(_Imsi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "MsIsdn")
    public JAXBElement<String> createMsIsdn(String value) {
        return new JAXBElement<String>(_MsIsdn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ServiceNumber")
    public JAXBElement<String> createServiceNumber(String value) {
        return new JAXBElement<String>(_ServiceNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SuspendActionEnumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "Action")
    public JAXBElement<SuspendActionEnumType> createAction(SuspendActionEnumType value) {
        return new JAXBElement<SuspendActionEnumType>(_Action_QNAME, SuspendActionEnumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "Options")
    public JAXBElement<String> createOptions(String value) {
        return new JAXBElement<String>(_Options_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OverridenPrice")
    public JAXBElement<BigDecimal> createOverridenPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OverridenPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderName")
    public JAXBElement<String> createOrderName(String value) {
        return new JAXBElement<String>(_OrderName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "Reason")
    public JAXBElement<String> createReason(String value) {
        return new JAXBElement<String>(_Reason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OldShortCodeNumber")
    public JAXBElement<String> createOldShortCodeNumber(String value) {
        return new JAXBElement<String>(_OldShortCodeNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "CustomerAccountId")
    public JAXBElement<String> createCustomerAccountId(String value) {
        return new JAXBElement<String>(_CustomerAccountId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "BillingAccountName")
    public JAXBElement<String> createBillingAccountName(String value) {
        return new JAXBElement<String>(_BillingAccountName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "CustomerName")
    public JAXBElement<String> createCustomerName(String value) {
        return new JAXBElement<String>(_CustomerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DeviceMake")
    public JAXBElement<String> createDeviceMake(String value) {
        return new JAXBElement<String>(_DeviceMake_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ShortCodeType")
    public JAXBElement<String> createShortCodeType(String value) {
        return new JAXBElement<String>(_ShortCodeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BulkSMSTypeEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "BulkSMSType")
    public JAXBElement<BulkSMSTypeEnum> createBulkSMSType(BulkSMSTypeEnum value) {
        return new JAXBElement<BulkSMSTypeEnum>(_BulkSMSType_QNAME, BulkSMSTypeEnum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderUserId")
    public JAXBElement<String> createOrderUserId(String value) {
        return new JAXBElement<String>(_OrderUserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "WaveOff")
    public JAXBElement<String> createWaveOff(String value) {
        return new JAXBElement<String>(_WaveOff_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "RoamingDeposit")
    public JAXBElement<String> createRoamingDeposit(String value) {
        return new JAXBElement<String>(_RoamingDeposit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "CreditScoreDate")
    public JAXBElement<XMLGregorianCalendar> createCreditScoreDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreditScoreDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ServiceNo")
    public JAXBElement<String> createServiceNo(String value) {
        return new JAXBElement<String>(_ServiceNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "CugId")
    public JAXBElement<String> createCugId(String value) {
        return new JAXBElement<String>(_CugId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HandSetDetailsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "HandSetDetails")
    public JAXBElement<HandSetDetailsType> createHandSetDetails(HandSetDetailsType value) {
        return new JAXBElement<HandSetDetailsType>(_HandSetDetails_QNAME, HandSetDetailsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "TerminationCharge")
    public JAXBElement<String> createTerminationCharge(String value) {
        return new JAXBElement<String>(_TerminationCharge_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ShortNumberAction")
    public JAXBElement<String> createShortNumberAction(String value) {
        return new JAXBElement<String>(_ShortNumberAction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ChannelTrackingId")
    public JAXBElement<String> createChannelTrackingId(String value) {
        return new JAXBElement<String>(_ChannelTrackingId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderAction")
    public JAXBElement<String> createOrderAction(String value) {
        return new JAXBElement<String>(_OrderAction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderCreatedDate")
    public JAXBElement<XMLGregorianCalendar> createOrderCreatedDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OrderCreatedDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "UnsuspendFlag")
    public JAXBElement<Boolean> createUnsuspendFlag(Boolean value) {
        return new JAXBElement<Boolean>(_UnsuspendFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "BarringType")
    public JAXBElement<String> createBarringType(String value) {
        return new JAXBElement<String>(_BarringType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "SuspendedIndicator")
    public JAXBElement<String> createSuspendedIndicator(String value) {
        return new JAXBElement<String>(_SuspendedIndicator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ServiceSuspensionDescription")
    public JAXBElement<String> createServiceSuspensionDescription(String value) {
        return new JAXBElement<String>(_ServiceSuspensionDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "CollectedOn")
    public JAXBElement<XMLGregorianCalendar> createCollectedOn(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CollectedOn_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "WaveOffReason")
    public JAXBElement<String> createWaveOffReason(String value) {
        return new JAXBElement<String>(_WaveOffReason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OldMsIsdn")
    public JAXBElement<String> createOldMsIsdn(String value) {
        return new JAXBElement<String>(_OldMsIsdn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceTypeEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ServiceType")
    public JAXBElement<ServiceTypeEnum> createServiceType(ServiceTypeEnum value) {
        return new JAXBElement<ServiceTypeEnum>(_ServiceType_QNAME, ServiceTypeEnum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "BarringAction")
    public JAXBElement<String> createBarringAction(String value) {
        return new JAXBElement<String>(_BarringAction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ContactNo")
    public JAXBElement<String> createContactNo(String value) {
        return new JAXBElement<String>(_ContactNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DepositReceiptNo")
    public JAXBElement<String> createDepositReceiptNo(String value) {
        return new JAXBElement<String>(_DepositReceiptNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "SimNo")
    public JAXBElement<String> createSimNo(String value) {
        return new JAXBElement<String>(_SimNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "PlanType")
    public JAXBElement<String> createPlanType(String value) {
        return new JAXBElement<String>(_PlanType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "PlanEndDate")
    public JAXBElement<XMLGregorianCalendar> createPlanEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PlanEndDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "AccountNo")
    public JAXBElement<String> createAccountNo(String value) {
        return new JAXBElement<String>(_AccountNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ShortCodeNumber")
    public JAXBElement<String> createShortCodeNumber(String value) {
        return new JAXBElement<String>(_ShortCodeNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DepositDate")
    public JAXBElement<XMLGregorianCalendar> createDepositDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DepositDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DepositAmount")
    public JAXBElement<BigDecimal> createDepositAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DepositAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "EmailId")
    public JAXBElement<String> createEmailId(String value) {
        return new JAXBElement<String>(_EmailId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderServiceType")
    public JAXBElement<String> createOrderServiceType(String value) {
        return new JAXBElement<String>(_OrderServiceType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdTypeEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "IdType")
    public JAXBElement<IdTypeEnum> createIdType(IdTypeEnum value) {
        return new JAXBElement<IdTypeEnum>(_IdType_QNAME, IdTypeEnum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "SpendingCap")
    public JAXBElement<String> createSpendingCap(String value) {
        return new JAXBElement<String>(_SpendingCap_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotificationLanguageEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "NotificationLanguage")
    public JAXBElement<NotificationLanguageEnum> createNotificationLanguage(NotificationLanguageEnum value) {
        return new JAXBElement<NotificationLanguageEnum>(_NotificationLanguage_QNAME, NotificationLanguageEnum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OldSimNo")
    public JAXBElement<String> createOldSimNo(String value) {
        return new JAXBElement<String>(_OldSimNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderStartDate")
    public JAXBElement<XMLGregorianCalendar> createOrderStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OrderStartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "AccountName")
    public JAXBElement<String> createAccountName(String value) {
        return new JAXBElement<String>(_AccountName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "PortType")
    public JAXBElement<String> createPortType(String value) {
        return new JAXBElement<String>(_PortType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ShortNumber")
    public JAXBElement<String> createShortNumber(String value) {
        return new JAXBElement<String>(_ShortNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "Id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ServiceChargeFlag")
    public JAXBElement<Boolean> createServiceChargeFlag(Boolean value) {
        return new JAXBElement<Boolean>(_ServiceChargeFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OldShortNumber")
    public JAXBElement<String> createOldShortNumber(String value) {
        return new JAXBElement<String>(_OldShortNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ContractStartDate")
    public JAXBElement<XMLGregorianCalendar> createContractStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ContractStartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DepositPaymentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DepositPayment")
    public JAXBElement<DepositPaymentType> createDepositPayment(DepositPaymentType value) {
        return new JAXBElement<DepositPaymentType>(_DepositPayment_QNAME, DepositPaymentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderCreatedDateMin")
    public JAXBElement<XMLGregorianCalendar> createOrderCreatedDateMin(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OrderCreatedDateMin_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "PlanName")
    public JAXBElement<String> createPlanName(String value) {
        return new JAXBElement<String>(_PlanName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ShortCodeCategory")
    public JAXBElement<String> createShortCodeCategory(String value) {
        return new JAXBElement<String>(_ShortCodeCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderStatus")
    public JAXBElement<String> createOrderStatus(String value) {
        return new JAXBElement<String>(_OrderStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "WaiverReason")
    public JAXBElement<String> createWaiverReason(String value) {
        return new JAXBElement<String>(_WaiverReason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "SimChargeFlag")
    public JAXBElement<Boolean> createSimChargeFlag(Boolean value) {
        return new JAXBElement<Boolean>(_SimChargeFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "CreditScore")
    public JAXBElement<String> createCreditScore(String value) {
        return new JAXBElement<String>(_CreditScore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderCreatedDateMax")
    public JAXBElement<XMLGregorianCalendar> createOrderCreatedDateMax(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OrderCreatedDateMax_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "EarlyTerminationFlag")
    public JAXBElement<String> createEarlyTerminationFlag(String value) {
        return new JAXBElement<String>(_EarlyTerminationFlag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ContractEndDate")
    public JAXBElement<XMLGregorianCalendar> createContractEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ContractEndDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "OrderResumeDate")
    public JAXBElement<XMLGregorianCalendar> createOrderResumeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OrderResumeDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "CustomerAccountName")
    public JAXBElement<String> createCustomerAccountName(String value) {
        return new JAXBElement<String>(_CustomerAccountName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "TerminationNotes")
    public JAXBElement<String> createTerminationNotes(String value) {
        return new JAXBElement<String>(_TerminationNotes_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "BAAccountNo")
    public JAXBElement<String> createBAAccountNo(String value) {
        return new JAXBElement<String>(_BAAccountNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "DealName")
    public JAXBElement<String> createDealName(String value) {
        return new JAXBElement<String>(_DealName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "PlanStartDate")
    public JAXBElement<XMLGregorianCalendar> createPlanStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PlanStartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "ServiceLevelDeposit")
    public JAXBElement<String> createServiceLevelDeposit(String value) {
        return new JAXBElement<String>(_ServiceLevelDeposit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "PlanAction")
    public JAXBElement<String> createPlanAction(String value) {
        return new JAXBElement<String>(_PlanAction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddActionPlanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/OEP/OrderManagement/Order/V1", name = "Plan", scope = AddOrderM2MType.class)
    public JAXBElement<AddActionPlanType> createAddOrderM2MTypePlan(AddActionPlanType value) {
        return new JAXBElement<AddActionPlanType>(_AddOrderM2MTypePlan_QNAME, AddActionPlanType.class, AddOrderM2MType.class, value);
    }

}
