//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 06:34:48 PM IST 
//


package com.oracle.oep.order.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AddActionPlanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddActionPlanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}PlanName"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}OverridenPrice" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}PlanStartDate"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}PlanEndDate" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}PlanAction" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderPlanType", propOrder = {
    "planName",
    "overridenPrice",
    "planStartDate",
    "planEndDate",
    "planAction"
})
public class OrderPlanType {

    @XmlElement(name = "PlanName", required = true)
    protected String planName;
    @XmlElement(name = "OverridenPrice")
    protected BigDecimal overridenPrice;
    @XmlElement(name = "PlanStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar planStartDate;
    @XmlElement(name = "PlanEndDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar planEndDate;
    @XmlElement(name = "PlanAction")
    protected String planAction;

    /**
     * Gets the value of the planName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * Sets the value of the planName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanName(String value) {
        this.planName = value;
    }

    /**
     * Gets the value of the overridenPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOverridenPrice() {
        return overridenPrice;
    }

    /**
     * Sets the value of the overridenPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOverridenPrice(BigDecimal value) {
        this.overridenPrice = value;
    }

    /**
     * Gets the value of the planStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlanStartDate() {
        return planStartDate;
    }

    /**
     * Sets the value of the planStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlanStartDate(XMLGregorianCalendar value) {
        this.planStartDate = value;
    }

    /**
     * Gets the value of the planEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlanEndDate() {
        return planEndDate;
    }

    /**
     * Sets the value of the planEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlanEndDate(XMLGregorianCalendar value) {
        this.planEndDate = value;
    }

    /**
     * Gets the value of the planAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanAction() {
        return planAction;
    }

    /**
     * Sets the value of the planAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanAction(String value) {
        this.planAction = value;
    }

}
