//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 06:34:48 PM IST 
//


package com.oracle.oep.order.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessCugOrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessCugOrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}CugId"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}BAAccountNo" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}CugAction" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ServiceNumber" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ShortNumberAction" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ShortNumber" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}OldShortNumber" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ChannelTrackingId"/>
 *         &lt;element name="ChannelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessCugOrderType", propOrder = {
    "cugId",
    "baAccountNo",
    "cugAction",
    "serviceNumber",
    "shortNumberAction",
    "shortNumber",
    "oldShortNumber",
    "channelTrackingId",
    "channelName"
})
public class ProcessCugOrderType {

    @XmlElement(name = "CugId", required = true)
    protected String cugId;
    @XmlElement(name = "BAAccountNo")
    protected String baAccountNo;
    @XmlElement(name = "CugAction")
    protected String cugAction;
    @XmlElement(name = "ServiceNumber")
    protected String serviceNumber;
    @XmlElement(name = "ShortNumberAction")
    protected String shortNumberAction;
    @XmlElement(name = "ShortNumber")
    protected String shortNumber;
    @XmlElement(name = "OldShortNumber")
    protected String oldShortNumber;
    @XmlElement(name = "ChannelTrackingId", required = true)
    protected String channelTrackingId;
    @XmlElement(name = "ChannelName", required = true)
    protected String channelName;

    /**
     * Gets the value of the cugId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCugId() {
        return cugId;
    }

    /**
     * Sets the value of the cugId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCugId(String value) {
        this.cugId = value;
    }

    /**
     * Gets the value of the baAccountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBAAccountNo() {
        return baAccountNo;
    }

    /**
     * Sets the value of the baAccountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBAAccountNo(String value) {
        this.baAccountNo = value;
    }

    /**
     * Gets the value of the cugAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCugAction() {
        return cugAction;
    }

    /**
     * Sets the value of the cugAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCugAction(String value) {
        this.cugAction = value;
    }

    /**
     * Gets the value of the serviceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceNumber() {
        return serviceNumber;
    }

    /**
     * Sets the value of the serviceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceNumber(String value) {
        this.serviceNumber = value;
    }

    /**
     * Gets the value of the shortNumberAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortNumberAction() {
        return shortNumberAction;
    }

    /**
     * Sets the value of the shortNumberAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortNumberAction(String value) {
        this.shortNumberAction = value;
    }

    /**
     * Gets the value of the shortNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortNumber() {
        return shortNumber;
    }

    /**
     * Sets the value of the shortNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortNumber(String value) {
        this.shortNumber = value;
    }

    /**
     * Gets the value of the oldShortNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldShortNumber() {
        return oldShortNumber;
    }

    /**
     * Sets the value of the oldShortNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldShortNumber(String value) {
        this.oldShortNumber = value;
    }

    /**
     * Gets the value of the channelTrackingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelTrackingId() {
        return channelTrackingId;
    }

    /**
     * Sets the value of the channelTrackingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelTrackingId(String value) {
        this.channelTrackingId = value;
    }

    /**
     * Gets the value of the channelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * Sets the value of the channelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelName(String value) {
        this.channelName = value;
    }

}
