//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 06:34:48 PM IST 
//


package com.oracle.oep.order.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessQueryOrderResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessQueryOrderResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListOfOrders" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ListOfOEPQueryOrderResponseType"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessQueryOrderResponseType", propOrder = {
    "listOfOrders",
    "status"
})
public class ProcessQueryOrderResponseType {

    @XmlElement(name = "ListOfOrders", required = true)
    protected ListOfOEPQueryOrderResponseType listOfOrders;
    @XmlElement(name = "Status", required = true)
    protected String status;

    /**
     * Gets the value of the listOfOrders property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfOEPQueryOrderResponseType }
     *     
     */
    public ListOfOEPQueryOrderResponseType getListOfOrders() {
        return listOfOrders;
    }

    /**
     * Sets the value of the listOfOrders property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfOEPQueryOrderResponseType }
     *     
     */
    public void setListOfOrders(ListOfOEPQueryOrderResponseType value) {
        this.listOfOrders = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
