//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 06:34:48 PM IST 
//


package com.oracle.oep.order.model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProcessAddOnManagmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessAddOnManagmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ServiceIdentifier"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ServiceType" minOccurs="0"/>
 *         &lt;element name="BasePackageName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddOnPackageName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}OverridenPrice" minOccurs="0"/>
 *         &lt;element name="Action" type="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}AddonActionEnum"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DeviceMake" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DeviceType" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DepositReceiptNo" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}CollectedOn" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DepositAmount" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}DepositType" minOccurs="0"/>
 *         &lt;element name="BillingIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChannelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/OrderManagement/Order/V1}ChannelTrackingId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessAddOnManagmentType", propOrder = {
    "serviceIdentifier",
    "loginId",
    "serviceType",
    "basePackageName",
    "addOnPackageName",
    "overridenPrice",
    "action",
    "deviceMake",
    "deviceType",
    "depositReceiptNo",
    "collectedOn",
    "depositAmount",
    "depositType",
    "billingIndicator",
    "channelName",
    "channelTrackingId"
})
public class ProcessAddOnManagmentType {

    @XmlElement(name = "ServiceIdentifier", required = true)
    protected String serviceIdentifier;    
    @XmlElement(name = "LoginId", required = true)
    protected String loginId;
    @XmlElement(name = "ServiceType")
    @XmlSchemaType(name = "string")
    protected ServiceTypeEnum serviceType;
    @XmlElement(name = "BasePackageName")
    protected String basePackageName;
    @XmlElement(name = "AddOnPackageName", required = true)
    protected String addOnPackageName;
    @XmlElement(name = "OverridenPrice")
    protected BigDecimal overridenPrice;
    @XmlElement(name = "Action", required = true)
    @XmlSchemaType(name = "string")
    protected AddonActionEnum action;
    @XmlElement(name = "DeviceMake")
    protected String deviceMake;
    @XmlElement(name = "DeviceType")
    protected String deviceType;
    @XmlElement(name = "DepositReceiptNo")
    protected String depositReceiptNo;
    @XmlElement(name = "CollectedOn")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar collectedOn;
    @XmlElement(name = "DepositAmount")
    protected BigDecimal depositAmount;
    @XmlElement(name = "DepositType")
    protected String depositType;
    @XmlElement(name = "BillingIndicator")
    protected String billingIndicator;
    @XmlElement(name = "ChannelName", required = true)
    protected String channelName;
    @XmlElement(name = "ChannelTrackingId", required = true)
    protected String channelTrackingId;

    /**
     * Gets the value of the serviceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceIdentifier() {
        return serviceIdentifier;
    }

    /**
     * Sets the value of the serviceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceIdentifier(String value) {
        this.serviceIdentifier = value;
    }
    
    /**
     * Gets the value of the loginId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * Sets the value of the loginId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginId(String value) {
        this.loginId = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceTypeEnum }
     *     
     */
    public ServiceTypeEnum getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceTypeEnum }
     *     
     */
    public void setServiceType(ServiceTypeEnum value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the basePackageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasePackageName() {
        return basePackageName;
    }

    /**
     * Sets the value of the basePackageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasePackageName(String value) {
        this.basePackageName = value;
    }

    /**
     * Gets the value of the addOnPackageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddOnPackageName() {
        return addOnPackageName;
    }

    /**
     * Sets the value of the addOnPackageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddOnPackageName(String value) {
        this.addOnPackageName = value;
    }
    
    /**
     * Gets the value of the overridenPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOverridenPrice() {
        return overridenPrice;
    }

    /**
     * Sets the value of the overridenPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOverridenPrice(BigDecimal value) {
        this.overridenPrice = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link AddonActionEnum }
     *     
     */
    public AddonActionEnum getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddonActionEnum }
     *     
     */
    public void setAction(AddonActionEnum value) {
        this.action = value;
    }

    /**
     * Gets the value of the depositReceiptNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositReceiptNo() {
        return depositReceiptNo;
    }

    /**
     * Sets the value of the depositReceiptNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositReceiptNo(String value) {
        this.depositReceiptNo = value;
    }

    /**
     * Gets the value of the collectedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCollectedOn() {
        return collectedOn;
    }

    /**
     * Sets the value of the collectedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCollectedOn(XMLGregorianCalendar value) {
        this.collectedOn = value;
    }

    /**
     * Gets the value of the depositAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDepositAmount() {
        return depositAmount;
    }

    /**
     * Sets the value of the depositAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDepositAmount(BigDecimal value) {
        this.depositAmount = value;
    }

    /**
     * Gets the value of the depositType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositType() {
        return depositType;
    }

    /**
     * Sets the value of the depositType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositType(String value) {
        this.depositType = value;
    }
    
    /**
     * Gets the value of the billingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingIndicator() {
        return billingIndicator;
    }

    /**
     * Sets the value of the billingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingIndicator(String value) {
        this.billingIndicator = value;
    }

    /**
     * Gets the value of the channelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * Sets the value of the channelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelName(String value) {
        this.channelName = value;
    }

    /**
     * Gets the value of the channelTrackingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelTrackingId() {
        return channelTrackingId;
    }

    /**
     * Sets the value of the channelTrackingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelTrackingId(String value) {
        this.channelTrackingId = value;
    }

	public String getDeviceMake() {
		return deviceMake;
	}

	public void setDeviceMake(String deviceMake) {
		this.deviceMake = deviceMake;
	}

	public String getDeviceType() {
		return deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

    
}
