//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.05 at 06:34:48 PM IST 
//


package com.oracle.oep.order.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Mobile"/>
 *     &lt;enumeration value="BB"/>
 *     &lt;enumeration value="SC"/>
 *     &lt;enumeration value="Bulk SMS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ServiceTypeEnum")
@XmlEnum
public enum ServiceTypeEnum {

    @XmlEnumValue("Mobile")
    MOBILE("Mobile"),
    BB("BB"),
    SC("SC"),
    @XmlEnumValue("Bulk SMS")
    BULK_SMS("Bulk SMS");
    private final String value;

    ServiceTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceTypeEnum fromValue(String v) {
        for (ServiceTypeEnum c: ServiceTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
