//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 11:55:57 AM IST 
//


package com.oracle.oep.notif.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.oep.notif.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AccountNo_QNAME = new QName("http://xmlns.oracle.com/communications/schemas/CRMSync", "AccountNo");
    private final static QName _Channel_QNAME = new QName("http://xmlns.oracle.com/communications/schemas/CRMSync", "Channel");
    private final static QName _EventDescr_QNAME = new QName("http://xmlns.oracle.com/communications/schemas/CRMSync", "EventDescr");
    private final static QName _ServiceNo_QNAME = new QName("http://xmlns.oracle.com/communications/schemas/CRMSync", "ServiceNo");
    private final static QName _FailureCode_QNAME = new QName("http://xmlns.oracle.com/communications/schemas/CRMSync", "FailureCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.oep.notif.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotifChangeRatePlanFailure }
     * 
     */
    public NotifChangeRatePlanFailure createNotifChangeRatePlanFailure() {
        return new NotifChangeRatePlanFailure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/schemas/CRMSync", name = "AccountNo")
    public JAXBElement<String> createAccountNo(String value) {
        return new JAXBElement<String>(_AccountNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/schemas/CRMSync", name = "Channel")
    public JAXBElement<String> createChannel(String value) {
        return new JAXBElement<String>(_Channel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/schemas/CRMSync", name = "EventDescr")
    public JAXBElement<String> createEventDescr(String value) {
        return new JAXBElement<String>(_EventDescr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/schemas/CRMSync", name = "ServiceNo")
    public JAXBElement<Long> createServiceNo(Long value) {
        return new JAXBElement<Long>(_ServiceNo_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/schemas/CRMSync", name = "FailureCode")
    public JAXBElement<String> createFailureCode(String value) {
        return new JAXBElement<String>(_FailureCode_QNAME, String.class, null, value);
    }

}
