//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.23 at 12:02:59 PM IST 
//


package com.oracle.oep.viewusage.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/ViewUsage/V1}POID"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/ViewUsage/V1}CUS_FLD_SERVICE_IDENTIFIER"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/ViewUsage/V1}USAGE_CATEGORY"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/ViewUsage/V1}PROGRAM_NAME"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/ViewUsage/V1}USER_NAME"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/ViewUsage/V1}USAGE_END_T"/>
 *         &lt;element ref="{http://xmlns.oracle.com/OEP/ViewUsage/V1}USAGE_START_T"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "poid",
    "cusfldserviceidentifier",
    "usagecategory",
    "programname",
    "username",
    "usageendt",
    "usagestartt"
})
@XmlRootElement(name = "CUS_OP_SUBSCRIPTION_VIEW_USAGE_inputFlistRequest")
public class CUSOPSUBSCRIPTIONVIEWUSAGEInputFlistRequest {

    @XmlElement(name = "POID", required = true)
    protected String poid;
    @XmlElement(name = "CUS_FLD_SERVICE_IDENTIFIER", required = true)
    protected String cusfldserviceidentifier;
    @XmlElement(name = "USAGE_CATEGORY")
    protected int usagecategory;
    @XmlElement(name = "PROGRAM_NAME", required = true)
    protected String programname;
    @XmlElement(name = "USER_NAME", required = true)
    protected String username;
    @XmlElement(name = "USAGE_END_T")
    protected long usageendt;
    @XmlElement(name = "USAGE_START_T")
    protected long usagestartt;

    /**
     * Gets the value of the poid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOID() {
        return poid;
    }

    /**
     * Sets the value of the poid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOID(String value) {
        this.poid = value;
    }

    /**
     * Gets the value of the cusfldserviceidentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSFLDSERVICEIDENTIFIER() {
        return cusfldserviceidentifier;
    }

    /**
     * Sets the value of the cusfldserviceidentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSFLDSERVICEIDENTIFIER(String value) {
        this.cusfldserviceidentifier = value;
    }

    /**
     * Gets the value of the usagecategory property.
     * 
     */
    public int getUSAGECATEGORY() {
        return usagecategory;
    }

    /**
     * Sets the value of the usagecategory property.
     * 
     */
    public void setUSAGECATEGORY(int value) {
        this.usagecategory = value;
    }

    /**
     * Gets the value of the programname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROGRAMNAME() {
        return programname;
    }

    /**
     * Sets the value of the programname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROGRAMNAME(String value) {
        this.programname = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERNAME() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERNAME(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the usageendt property.
     * 
     */
    public long getUSAGEENDT() {
        return usageendt;
    }

    /**
     * Sets the value of the usageendt property.
     * 
     */
    public void setUSAGEENDT(long value) {
        this.usageendt = value;
    }

    /**
     * Gets the value of the usagestartt property.
     * 
     */
    public long getUSAGESTARTT() {
        return usagestartt;
    }

    /**
     * Sets the value of the usagestartt property.
     * 
     */
    public void setUSAGESTARTT(long value) {
        this.usagestartt = value;
    }

}
