//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 11:37:52 AM IST 
//


package com.oracle.oep.bulkordermanagement.order.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ProcessBulkOrderRequest" type="{http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1}ProcessBulkOrderRequestType" minOccurs="0"/>
 *         &lt;element name="QueryWithFileOrderIdRequest" type="{http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1}QueryWithFileOrderIdRequestType" minOccurs="0"/>
 *         &lt;element name="QueryWithBatchIdRequest" type="{http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1}QueryWithBatchIdRequestType" minOccurs="0"/>
 *         &lt;element name="QueryFailedRecordsRequest" type="{http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1}QueryFailedRecordsRequestType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processBulkOrderRequest",
    "queryWithFileOrderIdRequest",
    "queryWithBatchIdRequest",
    "queryFailedRecordsRequest"
})
@XmlRootElement(name = "BulkOrderEntryRequest")
public class BulkOrderEntryRequest {

    @XmlElement(name = "ProcessBulkOrderRequest")
    protected ProcessBulkOrderRequestType processBulkOrderRequest;
    @XmlElement(name = "QueryWithFileOrderIdRequest")
    protected QueryWithFileOrderIdRequestType queryWithFileOrderIdRequest;
    @XmlElement(name = "QueryWithBatchIdRequest")
    protected QueryWithBatchIdRequestType queryWithBatchIdRequest;
    @XmlElement(name = "QueryFailedRecordsRequest")
    protected QueryFailedRecordsRequestType queryFailedRecordsRequest;

    /**
     * Gets the value of the processBulkOrderRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessBulkOrderRequestType }
     *     
     */
    public ProcessBulkOrderRequestType getProcessBulkOrderRequest() {
        return processBulkOrderRequest;
    }

    /**
     * Sets the value of the processBulkOrderRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessBulkOrderRequestType }
     *     
     */
    public void setProcessBulkOrderRequest(ProcessBulkOrderRequestType value) {
        this.processBulkOrderRequest = value;
    }

    /**
     * Gets the value of the queryWithFileOrderIdRequest property.
     * 
     * @return
     *     possible object is
     *     {@link QueryWithFileOrderIdRequestType }
     *     
     */
    public QueryWithFileOrderIdRequestType getQueryWithFileOrderIdRequest() {
        return queryWithFileOrderIdRequest;
    }

    /**
     * Sets the value of the queryWithFileOrderIdRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryWithFileOrderIdRequestType }
     *     
     */
    public void setQueryWithFileOrderIdRequest(QueryWithFileOrderIdRequestType value) {
        this.queryWithFileOrderIdRequest = value;
    }

    /**
     * Gets the value of the queryWithBatchIdRequest property.
     * 
     * @return
     *     possible object is
     *     {@link QueryWithBatchIdRequestType }
     *     
     */
    public QueryWithBatchIdRequestType getQueryWithBatchIdRequest() {
        return queryWithBatchIdRequest;
    }

    /**
     * Sets the value of the queryWithBatchIdRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryWithBatchIdRequestType }
     *     
     */
    public void setQueryWithBatchIdRequest(QueryWithBatchIdRequestType value) {
        this.queryWithBatchIdRequest = value;
    }

    /**
     * Gets the value of the queryFailedRecordsRequest property.
     * 
     * @return
     *     possible object is
     *     {@link QueryFailedRecordsRequestType }
     *     
     */
    public QueryFailedRecordsRequestType getQueryFailedRecordsRequest() {
        return queryFailedRecordsRequest;
    }

    /**
     * Sets the value of the queryFailedRecordsRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryFailedRecordsRequestType }
     *     
     */
    public void setQueryFailedRecordsRequest(QueryFailedRecordsRequestType value) {
        this.queryFailedRecordsRequest = value;
    }

}
