//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.26 at 11:37:52 AM IST 
//


package com.oracle.oep.bulkordermanagement.order.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.oep.bulkordermanagement.order.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderId_QNAME = new QName("http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", "OrderId");
    private final static QName _FileOrderId_QNAME = new QName("http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", "FileOrderId");
    private final static QName _FileName_QNAME = new QName("http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", "FileName");
    private final static QName _BatchId_QNAME = new QName("http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", "BatchId");
    private final static QName _FileDirectory_QNAME = new QName("http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", "FileDirectory");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.oep.bulkordermanagement.order.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BulkOrderEntryRequest }
     * 
     */
    public BulkOrderEntryRequest createBulkOrderEntryRequest() {
        return new BulkOrderEntryRequest();
    }

    /**
     * Create an instance of {@link ProcessBulkOrderRequestType }
     * 
     */
    public ProcessBulkOrderRequestType createProcessBulkOrderRequestType() {
        return new ProcessBulkOrderRequestType();
    }

    /**
     * Create an instance of {@link QueryWithFileOrderIdRequestType }
     * 
     */
    public QueryWithFileOrderIdRequestType createQueryWithFileOrderIdRequestType() {
        return new QueryWithFileOrderIdRequestType();
    }

    /**
     * Create an instance of {@link QueryWithBatchIdRequestType }
     * 
     */
    public QueryWithBatchIdRequestType createQueryWithBatchIdRequestType() {
        return new QueryWithBatchIdRequestType();
    }

    /**
     * Create an instance of {@link QueryFailedRecordsRequestType }
     * 
     */
    public QueryFailedRecordsRequestType createQueryFailedRecordsRequestType() {
        return new QueryFailedRecordsRequestType();
    }

    /**
     * Create an instance of {@link BulkOrderEntryResponse }
     * 
     */
    public BulkOrderEntryResponse createBulkOrderEntryResponse() {
        return new BulkOrderEntryResponse();
    }

    /**
     * Create an instance of {@link ProcessBulkOrderResponseType }
     * 
     */
    public ProcessBulkOrderResponseType createProcessBulkOrderResponseType() {
        return new ProcessBulkOrderResponseType();
    }

    /**
     * Create an instance of {@link QueryWithFileOrderIdResponseType }
     * 
     */
    public QueryWithFileOrderIdResponseType createQueryWithFileOrderIdResponseType() {
        return new QueryWithFileOrderIdResponseType();
    }

    /**
     * Create an instance of {@link QueryWithBatchIdResponseType }
     * 
     */
    public QueryWithBatchIdResponseType createQueryWithBatchIdResponseType() {
        return new QueryWithBatchIdResponseType();
    }

    /**
     * Create an instance of {@link QueryFailedRecordsResponseType }
     * 
     */
    public QueryFailedRecordsResponseType createQueryFailedRecordsResponseType() {
        return new QueryFailedRecordsResponseType();
    }

    /**
     * Create an instance of {@link FileOrderBatchType }
     * 
     */
    public FileOrderBatchType createFileOrderBatchType() {
        return new FileOrderBatchType();
    }

    /**
     * Create an instance of {@link QueryBatchesType }
     * 
     */
    public QueryBatchesType createQueryBatchesType() {
        return new QueryBatchesType();
    }

    /**
     * Create an instance of {@link QueryFailedBatchesResponseType }
     * 
     */
    public QueryFailedBatchesResponseType createQueryFailedBatchesResponseType() {
        return new QueryFailedBatchesResponseType();
    }

    /**
     * Create an instance of {@link BatchIdBatchType }
     * 
     */
    public BatchIdBatchType createBatchIdBatchType() {
        return new BatchIdBatchType();
    }

    /**
     * Create an instance of {@link QueryBatchIdResponseType }
     * 
     */
    public QueryBatchIdResponseType createQueryBatchIdResponseType() {
        return new QueryBatchIdResponseType();
    }

    /**
     * Create an instance of {@link QueryBatchesResponseType }
     * 
     */
    public QueryBatchesResponseType createQueryBatchesResponseType() {
        return new QueryBatchesResponseType();
    }

    /**
     * Create an instance of {@link BulkOrderParamsType }
     * 
     */
    public BulkOrderParamsType createBulkOrderParamsType() {
        return new BulkOrderParamsType();
    }

    /**
     * Create an instance of {@link FailOrderType }
     * 
     */
    public FailOrderType createFailOrderType() {
        return new FailOrderType();
    }

    /**
     * Create an instance of {@link QueryWithBatchIdType }
     * 
     */
    public QueryWithBatchIdType createQueryWithBatchIdType() {
        return new QueryWithBatchIdType();
    }

    /**
     * Create an instance of {@link BatchType }
     * 
     */
    public BatchType createBatchType() {
        return new BatchType();
    }

    /**
     * Create an instance of {@link OrderType }
     * 
     */
    public OrderType createOrderType() {
        return new OrderType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link QueryFailedBatchesType }
     * 
     */
    public QueryFailedBatchesType createQueryFailedBatchesType() {
        return new QueryFailedBatchesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", name = "OrderId")
    public JAXBElement<String> createOrderId(String value) {
        return new JAXBElement<String>(_OrderId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", name = "FileOrderId")
    public JAXBElement<String> createFileOrderId(String value) {
        return new JAXBElement<String>(_FileOrderId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", name = "FileName")
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", name = "BatchId")
    public JAXBElement<String> createBatchId(String value) {
        return new JAXBElement<String>(_BatchId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com.mv/OEP/BulkOrderManagement/Order/V1", name = "FileDirectory")
    public JAXBElement<String> createFileDirectory(String value) {
        return new JAXBElement<String>(_FileDirectory_QNAME, String.class, null, value);
    }

}
