//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.14 at 06:35:04 PM IST 
//


package com.oracle.oep.brm.opcode.root;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="opcodeName" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
 *         &lt;element name="inputXml" type="{http://www.w3.org/2001/XMLSchema}string" form="unqualified"/>
 *         &lt;element name="m_SchemaFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="unqualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opcodeName",
    "inputXml",
    "mSchemaFile"
})
@XmlRootElement(name = "opcode")
public class Opcode {

    @XmlElement(required = true)
    protected String opcodeName;
    @XmlElement(required = true)
    protected String inputXml;
    @XmlElement(name = "m_SchemaFile")
    protected String mSchemaFile;

    /**
     * Gets the value of the opcodeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpcodeName() {
        return opcodeName;
    }

    /**
     * Sets the value of the opcodeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpcodeName(String value) {
        this.opcodeName = value;
    }

    /**
     * Gets the value of the inputXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputXml() {
        return inputXml;
    }

    /**
     * Sets the value of the inputXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputXml(String value) {
        this.inputXml = value;
    }

    /**
     * Gets the value of the mSchemaFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSchemaFile() {
        return mSchemaFile;
    }

    /**
     * Sets the value of the mSchemaFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSchemaFile(String value) {
        this.mSchemaFile = value;
    }

}
