//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.14 at 06:35:24 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.oracle.com/BRM/schemas/BusinessOpcodes/")
package com.oracle.oep.brm.opcode.root;
