//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 02:50:19 PM IST 
//


package com.oracle.oep.osm.order.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}ProcessSalesOrderFulfillmentEBM"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processSalesOrderFulfillmentEBM"
})
@XmlRootElement(name = "CreateOrder", namespace = "http://xmlns.oracle.com/communications/ordermanagement")
public class CreateOrder {

    @XmlElement(name = "ProcessSalesOrderFulfillmentEBM", required = true)
    protected ProcessSalesOrderFulfillmentEBM processSalesOrderFulfillmentEBM;

    /**
     * Gets the value of the processSalesOrderFulfillmentEBM property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessSalesOrderFulfillmentEBM }
     *     
     */
    public ProcessSalesOrderFulfillmentEBM getProcessSalesOrderFulfillmentEBM() {
        return processSalesOrderFulfillmentEBM;
    }

    /**
     * Sets the value of the processSalesOrderFulfillmentEBM property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessSalesOrderFulfillmentEBM }
     *     
     */
    public void setProcessSalesOrderFulfillmentEBM(ProcessSalesOrderFulfillmentEBM value) {
        this.processSalesOrderFulfillmentEBM = value;
    }

}
