//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 02:50:19 PM IST 
//


package com.oracle.oep.osm.order.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}CUS_FLD_DEVICE_MODEL"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}CUS_FLD_DEVICE_TYPE"/>
 *       &lt;/sequence>
 *       &lt;attribute name="elem" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cusflddevicemodel",
    "cusflddevicetype"
})
@XmlRootElement(name = "CUS_FLD_HANDSET")
public class CUSFLDHANDSET {

    @XmlElement(name = "CUS_FLD_DEVICE_MODEL", required = true)
    protected String cusflddevicemodel;
    @XmlElement(name = "CUS_FLD_DEVICE_TYPE", required = true)
    protected BigInteger cusflddevicetype;
    @XmlAttribute(name = "elem", required = true)
    protected BigInteger elem;

    /**
     * Gets the value of the cusflddevicemodel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSFLDDEVICEMODEL() {
        return cusflddevicemodel;
    }

    /**
     * Sets the value of the cusflddevicemodel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSFLDDEVICEMODEL(String value) {
        this.cusflddevicemodel = value;
    }

    /**
     * Gets the value of the cusflddevicetype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCUSFLDDEVICETYPE() {
        return cusflddevicetype;
    }

    /**
     * Sets the value of the cusflddevicetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCUSFLDDEVICETYPE(BigInteger value) {
        this.cusflddevicetype = value;
    }

    /**
     * Gets the value of the elem property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getElem() {
        return elem;
    }

    /**
     * Sets the value of the elem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setElem(BigInteger value) {
        this.elem = value;
    }

}
