//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 03:58:27 PM IST 
//


package com.oracle.oep.osm.order.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}RECEIPT_NO"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}CUS_FLD_SERVICE_TYPE"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}CUS_FLD_COLLECTED_ON"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}AMOUNT"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}TYPE"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}OPTIONS"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}CUS_FLD_WAIVER_REASON"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}CUS_FLD_DEPOSIT_WAIVER" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}TYPE_STR"/>
 *       &lt;/sequence>
 *       &lt;attribute name="elem" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receiptno",
    "cusfldservicetype",
    "cusfldcollectedon",
    "amount",
    "type",
    "options",
    "cusfldwaiverreason",
    "cusflddepositwaiver",
    "typestr"
})
@XmlRootElement(name = "DEPOSITS")
public class DEPOSITS {

    @XmlElement(name = "RECEIPT_NO", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String receiptno;
    @XmlElement(name = "CUS_FLD_SERVICE_TYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String cusfldservicetype;
    @XmlElement(name = "CUS_FLD_COLLECTED_ON", required = true)
    @XmlSchemaType(name = "dateTime")
    protected long cusfldcollectedon;
    @XmlElement(name = "AMOUNT", required = true)
    protected BigDecimal amount;
    @XmlElement(name = "TYPE", required = true)
    protected BigInteger type;
    @XmlElement(name = "OPTIONS", required = true)
    protected BigInteger options;
    @XmlElement(name = "CUS_FLD_WAIVER_REASON", required = true)
    protected String cusfldwaiverreason;
    @XmlElement(name = "CUS_FLD_DEPOSIT_WAIVER")
    protected BigDecimal cusflddepositwaiver;
    @XmlElement(name = "TYPE_STR", required = true)
    protected String typestr;
    @XmlAttribute(name = "elem", required = true)
    protected BigInteger elem;

    /**
     * Gets the value of the receiptno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRECEIPTNO() {
        return receiptno;
    }

    /**
     * Sets the value of the receiptno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRECEIPTNO(String value) {
        this.receiptno = value;
    }

    /**
     * Gets the value of the cusfldservicetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSFLDSERVICETYPE() {
        return cusfldservicetype;
    }

    /**
     * Sets the value of the cusfldservicetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSFLDSERVICETYPE(String value) {
        this.cusfldservicetype = value;
    }

    /**
     * Gets the value of the cusfldcollectedon property.
     * 
     * @return
     *     possible object is
     *     {@link long }
     *     
     */
    public long getCUSFLDCOLLECTEDON() {
        return cusfldcollectedon;
    }

    /**
     * Sets the value of the cusfldcollectedon property.
     * 
     * @param value
     *     allowed object is
     *     {@link long }
     *     
     */
    public void setCUSFLDCOLLECTEDON(long value) {
        this.cusfldcollectedon = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAMOUNT() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAMOUNT(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTYPE(BigInteger value) {
        this.type = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOPTIONS() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOPTIONS(BigInteger value) {
        this.options = value;
    }

    /**
     * Gets the value of the cusfldwaiverreason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSFLDWAIVERREASON() {
        return cusfldwaiverreason;
    }

    /**
     * Sets the value of the cusfldwaiverreason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSFLDWAIVERREASON(String value) {
        this.cusfldwaiverreason = value;
    }

    /**
     * Gets the value of the cusflddepositwaiver property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCUSFLDDEPOSITWAIVER() {
        return cusflddepositwaiver;
    }

    /**
     * Sets the value of the cusflddepositwaiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCUSFLDDEPOSITWAIVER(BigDecimal value) {
        this.cusflddepositwaiver = value;
    }

    /**
     * Gets the value of the typestr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPESTR() {
        return typestr;
    }

    /**
     * Sets the value of the typestr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPESTR(String value) {
        this.typestr = value;
    }

    /**
     * Gets the value of the elem property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getElem() {
        return elem;
    }

    /**
     * Sets the value of the elem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setElem(BigInteger value) {
        this.elem = value;
    }

}
