//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.08 at 02:50:19 PM IST 
//


package com.oracle.oep.osm.order.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.oep.osm.order.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StartBillingOnFirstServiceUsageIndicator_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "StartBillingOnFirstServiceUsageIndicator");
    private final static QName _BarringType_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "BarringType");
    private final static QName _CsrId_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CsrId");
    private final static QName _CUSFLDWAIVERREASON_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CUS_FLD_WAIVER_REASON");
    private final static QName _OldPlanName_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "OldPlanName");
    private final static QName _PlanEndT_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "Plan_End_T");
    private final static QName _CUSFLDSCMINVAL_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CUS_FLD_SC_MIN_VAL");
    private final static QName _CUSFLDCREDITSCORE_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CUS_FLD_CREDIT_SCORE");
    private final static QName _LineOne_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "LineOne");
    private final static QName _NumberToBeReleased_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "NumberToBeReleased");
    private final static QName _TypeCode_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "TypeCode");
    private final static QName _TYPESTR_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "TYPE_STR");
    private final static QName _SuspendReason_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "SuspendReason");
    private final static QName _OrderDateTime_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "OrderDateTime");
    private final static QName _FulfillmentSuccessCode_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "FulfillmentSuccessCode");
    private final static QName _ServiceActionCode_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "ServiceActionCode");
    private final static QName _RequestedDeliveryDateTime_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "RequestedDeliveryDateTime");
    private final static QName _NetworkIndicator_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "NetworkIndicator");
    private final static QName _RECEIPTNO_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "RECEIPT_NO");
    private final static QName _CustomerAccountId_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CustomerAccountId");
    private final static QName _Number_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "Number");
    private final static QName _PlanStartT_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "Plan_Start_T");
    private final static QName _CUSFLDDEVICEMODEL_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CUS_FLD_DEVICE_MODEL");
    private final static QName _CUSFLDCOLLECTEDON_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CUS_FLD_COLLECTED_ON");
    private final static QName _CUSFLDSCMAXVAL_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CUS_FLD_SC_MAX_VAL");
    private final static QName _CUSFLDSERVICETYPE_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CUS_FLD_SERVICE_TYPE");
    private final static QName _ForwardToNumber_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "ForwardToNumber");
    private final static QName _MsIsdn_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "MsIsdn");
    private final static QName _FTNAction_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "FTNAction");
    private final static QName _OrderName_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "OrderName");
    private final static QName _OverridenPrice_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "OverridenPrice");
    private final static QName _AccountName_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "AccountName");
    private final static QName _CUSFLDSCACTUALVAL_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CUS_FLD_SC_ACTUAL_VAL");
    private final static QName _FulfillmentModeCode_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "FulfillmentModeCode");
    private final static QName _OrderSource_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "OrderSource");
    private final static QName _FulfillmentPriorityCode_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "FulfillmentPriorityCode");
    private final static QName _Value_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "Value");
    private final static QName _ServiceIndicator_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "ServiceIndicator");
    private final static QName _Code_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "Code");
    private final static QName _BarringLevel_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "BarringLevel");
    private final static QName _OPTIONS_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "OPTIONS");
    private final static QName _BillingAccountId_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "BillingAccountId");
    private final static QName _PlanType_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "Plan_Type");
    private final static QName _TYPE_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "TYPE");
    private final static QName _ID_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "ID");
    private final static QName _AMOUNT_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "AMOUNT");
    private final static QName _Name_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "Name");
    private final static QName _ServiceIdentifier_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "ServiceIdentifier");
    private final static QName _CUSFLDDEVICETYPE_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "CUS_FLD_DEVICE_TYPE");
    private final static QName _ParentLineIdentification_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "ParentLineIdentification");
    private final static QName _AccountId_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "AccountId");
    private final static QName _BillableLineItem_QNAME = new QName("http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", "BillableLineItem");
    
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.oep.osm.order.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateOrder }
     * 
     */
    public CreateOrder createCreateOrder() {
        return new CreateOrder();
    }

    /**
     * Create an instance of {@link ProcessSalesOrderFulfillmentEBM }
     * 
     */
    public ProcessSalesOrderFulfillmentEBM createProcessSalesOrderFulfillmentEBM() {
        return new ProcessSalesOrderFulfillmentEBM();
    }

    /**
     * Create an instance of {@link DataArea }
     * 
     */
    public DataArea createDataArea() {
        return new DataArea();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link ProcessSalesOrderFulfillment }
     * 
     */
    public ProcessSalesOrderFulfillment createProcessSalesOrderFulfillment() {
        return new ProcessSalesOrderFulfillment();
    }

    /**
     * Create an instance of {@link Identification }
     * 
     */
    public Identification createIdentification() {
        return new Identification();
    }

    /**
     * Create an instance of {@link ID }
     * 
     */
    public ID createID() {
        return new ID();
    }

    /**
     * Create an instance of {@link Revision }
     * 
     */
    public Revision createRevision() {
        return new Revision();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link SalesOrderLine }
     * 
     */
    public SalesOrderLine createSalesOrderLine() {
        return new SalesOrderLine();
    }

    /**
     * Create an instance of {@link MilestoneCode }
     * 
     */
    public MilestoneCode createMilestoneCode() {
        return new MilestoneCode();
    }

    /**
     * Create an instance of {@link ServiceAddress }
     * 
     */
    public ServiceAddress createServiceAddress() {
        return new ServiceAddress();
    }

    /**
     * Create an instance of {@link ItemReference }
     * 
     */
    public ItemReference createItemReference() {
        return new ItemReference();
    }

    /**
     * Create an instance of {@link ClassificationCode }
     * 
     */
    public ClassificationCode createClassificationCode() {
        return new ClassificationCode();
    }

    /**
     * Create an instance of {@link SpecificationGroup }
     * 
     */
    public SpecificationGroup createSpecificationGroup() {
        return new SpecificationGroup();
    }

    /**
     * Create an instance of {@link Specification }
     * 
     */
    public Specification createSpecification() {
        return new Specification();
    }

    /**
     * Create an instance of {@link CUSFLDHANDSET }
     * 
     */
    public CUSFLDHANDSET createCUSFLDHANDSET() {
        return new CUSFLDHANDSET();
    }

    /**
     * Create an instance of {@link CUSFLDCREDITSCORES }
     * 
     */
    public CUSFLDCREDITSCORES createCUSFLDCREDITSCORES() {
        return new CUSFLDCREDITSCORES();
    }

    /**
     * Create an instance of {@link DEPOSITS }
     * 
     */
    public DEPOSITS createDEPOSITS() {
        return new DEPOSITS();
    }

    /**
     * Create an instance of {@link SalesOrderSchedule }
     * 
     */
    public SalesOrderSchedule createSalesOrderSchedule() {
        return new SalesOrderSchedule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "StartBillingOnFirstServiceUsageIndicator")
    public JAXBElement<Boolean> createStartBillingOnFirstServiceUsageIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_StartBillingOnFirstServiceUsageIndicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "BarringType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBarringType(String value) {
        return new JAXBElement<String>(_BarringType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CsrId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCsrId(String value) {
        return new JAXBElement<String>(_CsrId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CUS_FLD_WAIVER_REASON")
    public JAXBElement<String> createCUSFLDWAIVERREASON(String value) {
        return new JAXBElement<String>(_CUSFLDWAIVERREASON_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "OldPlanName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOldPlanName(String value) {
        return new JAXBElement<String>(_OldPlanName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "Plan_End_T")
    public JAXBElement<XMLGregorianCalendar> createPlanEndT(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PlanEndT_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CUS_FLD_SC_MIN_VAL")
    public JAXBElement<BigDecimal> createCUSFLDSCMINVAL(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CUSFLDSCMINVAL_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CUS_FLD_CREDIT_SCORE")
    public JAXBElement<BigDecimal> createCUSFLDCREDITSCORE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CUSFLDCREDITSCORE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "LineOne")
    public JAXBElement<String> createLineOne(String value) {
        return new JAXBElement<String>(_LineOne_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "NumberToBeReleased")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNumberToBeReleased(String value) {
        return new JAXBElement<String>(_NumberToBeReleased_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "TypeCode")
    public JAXBElement<String> createTypeCode(String value) {
        return new JAXBElement<String>(_TypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "TYPE_STR")
    public JAXBElement<String> createTYPESTR(String value) {
        return new JAXBElement<String>(_TYPESTR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "SuspendReason")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSuspendReason(String value) {
        return new JAXBElement<String>(_SuspendReason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "OrderDateTime")
    public JAXBElement<XMLGregorianCalendar> createOrderDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_OrderDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "FulfillmentSuccessCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFulfillmentSuccessCode(String value) {
        return new JAXBElement<String>(_FulfillmentSuccessCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "ServiceActionCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createServiceActionCode(String value) {
        return new JAXBElement<String>(_ServiceActionCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "RequestedDeliveryDateTime")
    public JAXBElement<XMLGregorianCalendar> createRequestedDeliveryDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestedDeliveryDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "NetworkIndicator")
    public JAXBElement<Boolean> createNetworkIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_NetworkIndicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "RECEIPT_NO")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRECEIPTNO(String value) {
        return new JAXBElement<String>(_RECEIPTNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CustomerAccountId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCustomerAccountId(String value) {
        return new JAXBElement<String>(_CustomerAccountId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "Number")
    public JAXBElement<BigInteger> createNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_Number_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "Plan_Start_T")
    public JAXBElement<XMLGregorianCalendar> createPlanStartT(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PlanStartT_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CUS_FLD_DEVICE_MODEL")
    public JAXBElement<String> createCUSFLDDEVICEMODEL(String value) {
        return new JAXBElement<String>(_CUSFLDDEVICEMODEL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CUS_FLD_COLLECTED_ON")
    public JAXBElement<XMLGregorianCalendar> createCUSFLDCOLLECTEDON(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CUSFLDCOLLECTEDON_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CUS_FLD_SC_MAX_VAL")
    public JAXBElement<BigDecimal> createCUSFLDSCMAXVAL(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CUSFLDSCMAXVAL_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CUS_FLD_SERVICE_TYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCUSFLDSERVICETYPE(String value) {
        return new JAXBElement<String>(_CUSFLDSERVICETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "ForwardToNumber")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createForwardToNumber(String value) {
        return new JAXBElement<String>(_ForwardToNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "MsIsdn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMsIsdn(String value) {
        return new JAXBElement<String>(_MsIsdn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "FTNAction")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFTNAction(String value) {
        return new JAXBElement<String>(_FTNAction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "OrderName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOrderName(String value) {
        return new JAXBElement<String>(_OrderName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "OverridenPrice")
    public JAXBElement<BigDecimal> createOverridenPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OverridenPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "AccountName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAccountName(String value) {
        return new JAXBElement<String>(_AccountName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CUS_FLD_SC_ACTUAL_VAL")
    public JAXBElement<BigDecimal> createCUSFLDSCACTUALVAL(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CUSFLDSCACTUALVAL_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "FulfillmentModeCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFulfillmentModeCode(String value) {
        return new JAXBElement<String>(_FulfillmentModeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "OrderSource")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOrderSource(String value) {
        return new JAXBElement<String>(_OrderSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "FulfillmentPriorityCode")
    public JAXBElement<BigInteger> createFulfillmentPriorityCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_FulfillmentPriorityCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "Value")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "ServiceIndicator")
    public JAXBElement<Boolean> createServiceIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_ServiceIndicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "Code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "BarringLevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBarringLevel(String value) {
        return new JAXBElement<String>(_BarringLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "OPTIONS")
    public JAXBElement<BigInteger> createOPTIONS(BigInteger value) {
        return new JAXBElement<BigInteger>(_OPTIONS_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "BillingAccountId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBillingAccountId(String value) {
        return new JAXBElement<String>(_BillingAccountId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "Plan_Type")
    public JAXBElement<BigInteger> createPlanType(BigInteger value) {
        return new JAXBElement<BigInteger>(_PlanType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "TYPE")
    public JAXBElement<BigInteger> createTYPE(BigInteger value) {
        return new JAXBElement<BigInteger>(_TYPE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createID(String value) {
        return new JAXBElement<String>(_ID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "AMOUNT")
    public JAXBElement<BigDecimal> createAMOUNT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_AMOUNT_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "ServiceIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createServiceIdentifier(String value) {
        return new JAXBElement<String>(_ServiceIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "CUS_FLD_DEVICE_TYPE")
    public JAXBElement<BigInteger> createCUSFLDDEVICETYPE(BigInteger value) {
        return new JAXBElement<BigInteger>(_CUSFLDDEVICETYPE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "ParentLineIdentification")
    public JAXBElement<ID> createParentLineIdentification(ID value) {
        return new JAXBElement<ID>(_ParentLineIdentification_QNAME, ID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "AccountId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAccountId(String value) {
        return new JAXBElement<String>(_AccountId_QNAME, String.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2", name = "BillableLineItem")
    public JAXBElement<Boolean> createBillableLineItem(Boolean value) {
        return new JAXBElement<Boolean>(_BillableLineItem_QNAME, Boolean.class, null, value);
    }

}
