//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 05:53:40 PM IST 
//


package com.oracle.oep.osm.order.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}Identification"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}ParentLineIdentification"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}AccountId"/>
 *           &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}BarringLevel"/>
 *           &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}BarringType"/>
 *           &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}AccountName"/>
 *           &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}BillingAccountId"/>
 *           &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}CustomerAccountId"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}ServiceActionCode"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}StartBillingOnFirstServiceUsageIndicator"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}FulfillmentModeCode"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}MilestoneCode"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}Status"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}ServiceAddress"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}ItemReference"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}SalesOrderSchedule"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}BillableLineItem" minOccurs="0"/>
 *         &lt;element ref="{http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2}ProvisionableLineItem" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identification",
    "parentLineIdentification",
    "accountId",
    "barringLevel",
    "barringType",
    "accountName",
    "billingAccountId",
    "customerAccountId",
    "serviceActionCode",
    "startBillingOnFirstServiceUsageIndicator",
    "fulfillmentModeCode",
    "milestoneCode",
    "status",
    "serviceAddress",
    "itemReference",
    "salesOrderSchedule",
    "billableLineItem",
    "provisionableLineItem"
})
@XmlRootElement(name = "SalesOrderLine")
public class SalesOrderLine {

    @XmlElement(name = "Identification", required = true)
    protected Identification identification;
    @XmlElement(name = "ParentLineIdentification", required = true)
    protected ID parentLineIdentification;
    @XmlElement(name = "AccountId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String accountId;
    @XmlElement(name = "BarringLevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String barringLevel;
    @XmlElement(name = "BarringType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String barringType;
    @XmlElement(name = "AccountName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String accountName;
    @XmlElement(name = "BillingAccountId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String billingAccountId;
    @XmlElement(name = "CustomerAccountId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String customerAccountId;
    @XmlElement(name = "ServiceActionCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String serviceActionCode;
    @XmlElement(name = "StartBillingOnFirstServiceUsageIndicator")
    protected boolean startBillingOnFirstServiceUsageIndicator;
    @XmlElement(name = "FulfillmentModeCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fulfillmentModeCode;
    @XmlElement(name = "MilestoneCode", required = true)
    protected MilestoneCode milestoneCode;
    @XmlElement(name = "Status", required = true)
    protected Status status;
    @XmlElement(name = "ServiceAddress", required = true)
    protected ServiceAddress serviceAddress;
    @XmlElement(name = "ItemReference", required = true)
    protected ItemReference itemReference;
    @XmlElement(name = "SalesOrderSchedule", required = true)
    protected SalesOrderSchedule salesOrderSchedule;
    @XmlElement(name = "BillableLineItem")
    protected Boolean billableLineItem;
    @XmlElement(name = "ProvisionableLineItem")
    protected String provisionableLineItem;

    /**
     * Gets the value of the identification property.
     * 
     * @return
     *     possible object is
     *     {@link Identification }
     *     
     */
    public Identification getIdentification() {
        return identification;
    }

    /**
     * Sets the value of the identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identification }
     *     
     */
    public void setIdentification(Identification value) {
        this.identification = value;
    }

    /**
     * Gets the value of the parentLineIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ID }
     *     
     */
    public ID getParentLineIdentification() {
        return parentLineIdentification;
    }

    /**
     * Sets the value of the parentLineIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ID }
     *     
     */
    public void setParentLineIdentification(ID value) {
        this.parentLineIdentification = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountId(String value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the barringLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarringLevel() {
        return barringLevel;
    }

    /**
     * Sets the value of the barringLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarringLevel(String value) {
        this.barringLevel = value;
    }

    /**
     * Gets the value of the barringType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarringType() {
        return barringType;
    }

    /**
     * Sets the value of the barringType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarringType(String value) {
        this.barringType = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the billingAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingAccountId() {
        return billingAccountId;
    }

    /**
     * Sets the value of the billingAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingAccountId(String value) {
        this.billingAccountId = value;
    }

    /**
     * Gets the value of the customerAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAccountId() {
        return customerAccountId;
    }

    /**
     * Sets the value of the customerAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAccountId(String value) {
        this.customerAccountId = value;
    }

    /**
     * Gets the value of the serviceActionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceActionCode() {
        return serviceActionCode;
    }

    /**
     * Sets the value of the serviceActionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceActionCode(String value) {
        this.serviceActionCode = value;
    }

    /**
     * Gets the value of the startBillingOnFirstServiceUsageIndicator property.
     * 
     */
    public boolean isStartBillingOnFirstServiceUsageIndicator() {
        return startBillingOnFirstServiceUsageIndicator;
    }

    /**
     * Sets the value of the startBillingOnFirstServiceUsageIndicator property.
     * 
     */
    public void setStartBillingOnFirstServiceUsageIndicator(boolean value) {
        this.startBillingOnFirstServiceUsageIndicator = value;
    }

    /**
     * Gets the value of the fulfillmentModeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFulfillmentModeCode() {
        return fulfillmentModeCode;
    }

    /**
     * Sets the value of the fulfillmentModeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFulfillmentModeCode(String value) {
        this.fulfillmentModeCode = value;
    }

    /**
     * Gets the value of the milestoneCode property.
     * 
     * @return
     *     possible object is
     *     {@link MilestoneCode }
     *     
     */
    public MilestoneCode getMilestoneCode() {
        return milestoneCode;
    }

    /**
     * Sets the value of the milestoneCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MilestoneCode }
     *     
     */
    public void setMilestoneCode(MilestoneCode value) {
        this.milestoneCode = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the serviceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceAddress }
     *     
     */
    public ServiceAddress getServiceAddress() {
        return serviceAddress;
    }

    /**
     * Sets the value of the serviceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceAddress }
     *     
     */
    public void setServiceAddress(ServiceAddress value) {
        this.serviceAddress = value;
    }

    /**
     * Gets the value of the itemReference property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReference }
     *     
     */
    public ItemReference getItemReference() {
        return itemReference;
    }

    /**
     * Sets the value of the itemReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReference }
     *     
     */
    public void setItemReference(ItemReference value) {
        this.itemReference = value;
    }

    /**
     * Gets the value of the salesOrderSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link SalesOrderSchedule }
     *     
     */
    public SalesOrderSchedule getSalesOrderSchedule() {
        return salesOrderSchedule;
    }

    /**
     * Sets the value of the salesOrderSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesOrderSchedule }
     *     
     */
    public void setSalesOrderSchedule(SalesOrderSchedule value) {
        this.salesOrderSchedule = value;
    }

    /**
     * Gets the value of the billableLineItem property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBillableLineItem() {
        return billableLineItem;
    }

    /**
     * Sets the value of the billableLineItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBillableLineItem(Boolean value) {
        this.billableLineItem = value;
    }

    /**
     * Gets the value of the provisionableLineItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvisionableLineItem() {
        return provisionableLineItem;
    }

    /**
     * Sets the value of the provisionableLineItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvisionableLineItem(String value) {
        this.provisionableLineItem = value;
    }

}
